"""Guard the direct-child limits for the SSH execution packages."""  # State the structural contract.

from __future__ import annotations  # Use current annotation behavior in the guard.

from pathlib import Path  # Resolve live and temporary package layouts.

import pytest  # Prove invalid package layouts fail closed.

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]  # Resolve the active worktree.
SSH_ROOT = REPOSITORY_ROOT / "src/operations/execution/ssh"  # Target the SSH package.
RUNTIME_ROOT = SSH_ROOT / "runtime"  # Target the nested runtime package.
EXPECTED_SSH_CHILDREN = {"batch", "command", "config", "connection", "runtime"}  # Define the five-child SSH layout.
EXPECTED_RUNTIME_CHILDREN = {"app_runner.py", "interactive_mode.py", "shell_execution"}  # Define the runtime layout.
REQUIRED_SHELL_MODULES = {"__init__.py", "shell_executor.py"}  # Require package metadata and the executor module.
MAX_CHILDREN = 5  # Enforce the repository hierarchy limit.


def visible_children(directory: Path) -> list[Path]:
    """Return direct structural children and exclude package metadata."""
    if not directory.is_dir():  # Fail when the target package cannot be measured.
        raise AssertionError(f"Missing package root: {directory}. Checked 0 children.")
    return [  # Exclude metadata and generated bytecode from the structural count.
        child for child in directory.iterdir() if child.name not in {"__init__.py", "__pycache__"}
    ]


def visible_packages(directory: Path) -> list[Path]:
    """Return direct child packages and exclude package metadata."""
    return [child for child in visible_children(directory) if child.is_dir()]


def validate_child_limit(directory: Path, package_name: str, packages_only: bool = False) -> list[Path]:
    """Return children when a package has no more than five structural children."""
    children = (
        visible_packages(directory) if packages_only else visible_children(directory)
    )  # Measure the package layout.
    if len(children) > MAX_CHILDREN:  # Reject a hierarchy that exceeds the project limit.
        raise AssertionError(
            f"Checked {len(children)} {package_name} children. "
            f"Maximum is {MAX_CHILDREN}: {sorted(child.name for child in children)}"
        )
    return children  # Supply the measured children for exact-layout assertions.


def validate_shell_execution_modules(runtime_root: Path) -> None:
    """Require the shell execution package to hold its metadata and executor."""
    shell_root = runtime_root / "shell_execution"  # Resolve the canonical shell package.
    if not shell_root.is_dir():  # Fail when the moved package is absent.
        raise AssertionError(f"Missing shell execution package: {shell_root}.")
    missing = sorted(  # Measure each required module before reporting a failure.
        module_name for module_name in REQUIRED_SHELL_MODULES if not (shell_root / module_name).is_file()
    )
    if missing:  # Reject a partial package move.
        raise AssertionError(f"Missing shell execution modules: {missing}.")


def test_ssh_has_expected_children_and_runtime_stays_within_limit() -> None:
    """Require the SSH package to hold five children and the runtime package to stay within five."""
    ssh_children = validate_child_limit(SSH_ROOT, "ssh", packages_only=True)  # Measure direct SSH child packages.
    ssh_names = {child.name for child in ssh_children}  # Compare stable child names.
    assert len(ssh_children) == 5, f"Checked {len(ssh_children)} ssh children: {sorted(ssh_names)}"
    assert ssh_names == EXPECTED_SSH_CHILDREN, f"Checked ssh children: {sorted(ssh_names)}"
    runtime_children = validate_child_limit(RUNTIME_ROOT, "runtime")  # Measure the nested runtime package.
    runtime_names = {child.name for child in runtime_children}  # Compare stable runtime child names.
    assert runtime_names == EXPECTED_RUNTIME_CHILDREN, f"Checked runtime children: {sorted(runtime_names)}"
    validate_shell_execution_modules(RUNTIME_ROOT)  # Require both moved shell package modules.


def test_ssh_child_limit_rejects_a_controlled_sixth_child(tmp_path: Path) -> None:
    """Prove that a sixth SSH child fails the package guard."""
    package_root = tmp_path / "ssh"  # Isolate the controlled invalid package.
    package_root.mkdir()  # Create the package root for the failure proof.
    for child_name in EXPECTED_SSH_CHILDREN:  # Reproduce the approved five-child layout.
        (package_root / child_name).mkdir()  # Create each structural child.
    (package_root / "sixth").mkdir()  # Add one forbidden direct child.

    with pytest.raises(AssertionError, match=r"Checked 6 ssh children"):  # Require the measured count.
        validate_child_limit(package_root, "ssh", packages_only=True)  # Exercise the invalid hierarchy directly.


def test_runtime_child_limit_rejects_a_controlled_sixth_child(tmp_path: Path) -> None:
    """Prove that a sixth runtime child fails the nested package guard."""
    package_root = tmp_path / "runtime"  # Isolate the controlled invalid package.
    package_root.mkdir()  # Create the runtime root for the failure proof.
    runtime_children = ["app_runner.py", "interactive_mode.py", "shell_execution", "fourth.py", "fifth.py"]
    for child_name in runtime_children:  # Reproduce five structural runtime children.
        target = package_root / child_name  # Resolve each expected child.
        target.mkdir() if target.suffix == "" else target.touch()  # Create a package or module by its shape.
    (package_root / "sixth.py").touch()  # Add one forbidden direct child.

    with pytest.raises(AssertionError, match=r"Checked 6 runtime children"):  # Require the measured count.
        validate_child_limit(package_root, "runtime")  # Exercise the invalid hierarchy directly.


def test_shell_execution_layout_rejects_a_missing_module(tmp_path: Path) -> None:
    """Prove that a missing moved shell module fails closed."""
    runtime_root = tmp_path / "runtime"  # Isolate the partial-move fixture.
    (runtime_root / "shell_execution").mkdir(parents=True)  # Create only the canonical package.
    (runtime_root / "shell_execution" / "__init__.py").touch()  # Leave the executor absent on purpose.

    with pytest.raises(AssertionError, match=r"Missing shell execution modules"):  # Require the missing-module report.
        validate_shell_execution_modules(runtime_root)  # Exercise the incomplete package directly.
