"""Ordered taxonomy rules for Juniper domain classification."""

from __future__ import annotations  # Keep annotations available for imported models.

from .models import DomainRule  # Share one immutable rule contract with the classifier.

GENERAL_DOMAIN = "juniper-general-reference"  # Use the contract fallback domain exactly.
SIGNAL_CONFIDENCE = {  # Rank signals so reports show how much evidence selected a domain.
    "title": 0.95,  # Trust titles first because they name the document purpose.
    "path": 0.90,  # Trust paths next because the harvester encodes subjects there.
    "category": 0.85,  # Trust categories when the source used a useful section.
    "heading": 0.75,  # Trust headings when front matter gives no clear signal.
    "content": 0.60,  # Treat body-only matches as weak because broad guides are noisy.
    "fallback": 0.20,  # Mark the required fallback as low confidence by design.
}
SIGNAL_ORDER = ("title", "path", "category", "heading", "content")  # State the scan order for every document.
DOCUMENT_TYPE_RULES = (  # Apply required document-type rules before normal domain rules.
    DomainRule(1, "juniper-software-lifecycle", ("release notes",), ("release-notes",)),  # Keep releases in lifecycle.
    DomainRule(2, "juniper-security-srx-firewall", ("srx", "vsrx", "csrx")),  # Route SRX names to firewall first.
)
DOMAIN_RULES = (  # Preserve the priority table from contracts/domain-taxonomy.md.
    DomainRule(
        1,
        "juniper-cli-reference",
        ("junos cli reference", "cli reference", "command reference", "statement reference"),
        ("cli-reference",),
    ),
    DomainRule(
        2,
        "juniper-evpn-vxlan-fabric",
        (
            "evpn",
            "vxlan",
            "evpn-vxlan",
            "ip fabric",
            "spine",
            "leaf",
            "virtual chassis",
            "mc-lag",
            "mpls l2vpn",
            "layer 2 vpn",
            "vpls",
        ),
    ),
    DomainRule(
        3,
        "juniper-sdwan-wan",
        ("session smart", "sd-wan", "sdwan", "wan assurance", "wan edge", "128 technology", "conductor", "branch wan"),
        (),
        (r"\bssr\b",),
    ),
    DomainRule(
        4,
        "juniper-routing-policy-firewall",
        (
            "routing policy",
            "firewall filter",
            "traffic policer",
            "class of service",
            "policy framework",
            "route filter",
            "prefix list",
        ),
        (),
        (r"\bcos\b",),
    ),
    DomainRule(
        5,
        "juniper-api-automation",
        (
            "api",
            "rest",
            "netconf",
            "yang",
            "pyez",
            "ansible",
            "automation",
            "script",
            "sdk",
            "developer",
            "webhook",
            "telemetry",
        ),
        ("api",),
    ),
    DomainRule(
        6,
        "juniper-software-lifecycle",
        ("release notes", "upgrade", "update", "interim", "fix", "end of life", "end of support"),
        ("release-notes", "migration"),
        (r"\beol\b", r"\beos\b"),
    ),
    DomainRule(
        7,
        "juniper-security-analytics-compliance",
        (
            "jsa",
            "secure analytics",
            "security analytics",
            "siem",
            "log collector",
            "dsm",
            "fips",
            "common criteria",
            "fedramp",
            "compliance",
            "validation report",
        ),
        ("security-and-compliance",),
    ),
    DomainRule(
        8,
        "juniper-security-vpn-threat",
        ("ipsec", "vpn", "utm", "idp", "ips", "threat", "sky atp", "advanced threat", "secure edge"),
    ),
    DomainRule(
        9,
        "juniper-security-srx-firewall",
        ("srx", "vsrx", "csrx", "firewall", "nat", "security director", "security gateway"),
    ),
    DomainRule(10, "juniper-routing-director-operations", ("routing director",)),
    DomainRule(
        11,
        "juniper-observability-operations",
        (
            "paragon",
            "northstar",
            "healthbot",
            "monitor",
            "monitoring",
            "analytics",
            "insights",
            "planner",
            "orchestration",
            "proactive",
            "service assurance",
        ),
    ),
    DomainRule(
        12,
        "juniper-subscriber-services",
        (
            "broadband subscriber",
            "subscriber management",
            "subscriber sessions",
            "bng",
            "aaa subscriber",
            "dynamic profiles",
            "pppoe",
            "dhcp subscriber",
        ),
    ),
    DomainRule(
        13,
        "juniper-mpls-transport",
        ("mpls", "ldp", "rsvp", "segment routing", "sr-mpls", "traffic engineering", "layer 3 vpn", "l3vpn"),
    ),
    DomainRule(
        14,
        "juniper-routing-protocols",
        (
            "bgp",
            "ospf",
            "isis",
            "is-is",
            "rip",
            "route reflection",
            "multicast",
            "pim",
            "igmp",
            "msdp",
            "routing protocol",
        ),
    ),
    DomainRule(
        15,
        "juniper-junos-fundamentals",
        (
            "junos",
            "configuration hierarchy",
            "commit",
            "rollback",
            "system services",
            "user management",
            "authentication",
            "routing engine",
            "chassis cluster",
            "interfaces",
        ),
    ),
    DomainRule(
        16, "juniper-datacenter-apstra", ("apstra", "data center", "datacenter", "intent-based", "sfs", "smart fabric")
    ),
    DomainRule(
        17,
        "juniper-cloud-native-contrail",
        (
            "contrail",
            "cloud native",
            "cloud-native",
            "cn2",
            "kubernetes",
            "openshift",
            "containerized",
            "cni",
            "virtual network",
        ),
    ),
    DomainRule(
        18,
        "juniper-mist-ai-cloud",
        (
            "mist",
            "marvis",
            "ai-native",
            "assurance",
            "premium analytics",
            "wi-fi",
            "wlan",
            "access point",
            "ble",
            "radio",
            "antenna",
            "location services",
        ),
        (),
        (r"\bap\d+\b",),
    ),
    DomainRule(
        19,
        "juniper-campus-branch-switching",
        ("campus", "branch", "switching", "switches", "switch", "ethernet switch", "wired access", "poe"),
        (),
        (r"\bex\d+\b", r"\bqfx\d+\b"),
    ),
    DomainRule(
        20,
        "juniper-hardware-platforms",
        (
            "datasheet",
            "data sheet",
            "hardware",
            "platform",
            "chassis",
            "line card",
            "mic",
            "pic",
            "fpc",
            "transceiver",
            "power supply",
            "fan tray",
            "module",
            "adapter",
            "optics",
            "cable",
        ),
        ("datasheets",),
    ),
    DomainRule(
        21,
        "juniper-installation-maintenance",
        ("installation", "install", "rack", "mount", "cabling", "replacement", "fru", "maintenance"),
        ("installation-guides", "configuration-guides", "administration-guides"),
    ),
    DomainRule(
        22,
        "juniper-training-learning",
        (
            "day one",
            "dayone",
            "getting started",
            "quick start",
            "quickstart",
            "lab",
            "learning",
            "certification",
            "exam",
            "student",
            "course",
        ),
    ),
    DomainRule(
        23,
        "juniper-business-solutions",
        (
            "case study",
            "solution brief",
            "white paper",
            "analyst report",
            "customer story",
            "industry",
        ),
        (
            "case-studies",
            "solution-briefs",
            "white-papers",
            "flyers",
            "infographics",
            "analyst-reports",
            "ebooks",
            "executive-briefs",
            "use-cases",
            "brochures",
            "factsheet",
            "editorials",
            "articles",
            "marketing-asset",
            "reference-architectures",
            "validation-reports",
            "design",
        ),
    ),
    DomainRule(
        24,
        "juniper-legal-corporate",
        (
            "anti-corruption",
            "code of conduct",
            "trademark",
            "privacy",
            "personal data",
            "conflict minerals",
            "accessibility",
            "esg",
            "cdp",
            "certificate",
        ),
        ("legal", "sustainability", "certificates", "service-descriptions"),
    ),
)
