"""Static menu operation descriptions for the web portal.

Provides operation metadata without requiring MistHelper imports
or API authentication. Used by wsgi.py to populate the operations
list when the portal starts independently from MistHelper CLI.

Warning: this file is generated. Run
``python scripts/generate_portal_menu_registry.py`` after adding or renaming an
operation. ``tests/guardrails/test_portal_menu_registry_sync.py`` fails when
this map drifts from ``OperationRegistry``.

The map holds every operation that ``OperationRegistry`` calls ``safe`` or
``interactive_safe``, because those are the two classes the portal may run.
"""

from src.utils.menu_entry import MenuEntry  # WHY: static rows must match the real menu row shape.

MENU_DESCRIPTIONS = {
    "1": "Export a list of all sites in the organization",
    "2": "Export a list of sites with location and timezone info",
    "3": "Export all sites using the 'list' sites API endpoint (to SiteList_ListAPI.csv, only if not already present)",
    "4": "Export all current guest users and last 7 days of historical guests to CSV",
    "5": "Export E911 report for the organization",
    "6": "Site Config Analysis - Scan all sites for zone, engagement dwell tag, and occupancy setting deviations",
    "7": "Site Inventory Health Analysis - Find sites with APs missing switches/gateways, or with offline infrastructure",
    "8": "Export the full inventory of devices in the organization",
    "9": "Export a list of all devices in the organization",
    "10": "Export a list of all devices with associated site and address info",
    "11": "Export a list of gateways with associated site and address info",
    "12": "Export combined inventory with site and address info by calendar week",
    "13": "Export org device model counts, firmware version distribution, and versions per model (MSP-aware)",
    "15": "Export statistics for all devices in the organization",
    "16": "Export VPN peer path statistics for the organization",
    "17": "Export all switch virtual chassis (VC/stacking) stats to CSV",
    "20": "Export all organization alarms from the past day",
    "21": "Export all device events from the past 24 hours",
    "22": "Export audit logs for the organization (last 24 hours)",
    "23": "Export self (admin account) audit log",
    "24": "Export security events for the organization",
    "25": "Audit Log Analysis - Mermaid timeline + interactive HTML report",
    "26": "Offline Device Report",
    "27": "Export wireless client statistics for the organization",
    "28": "Export wired client statistics for the organization",
    "29": "Export rogue client detections for the organization",
    "30": "Export rogue AP detections for the organization",
    "31": "Export gateway management overlay IPs grouped by template association",
    "32": "Export gateway templates from the organization",
    "33": "Export synthetic test results for all gateways",
    "34": "Export all synthetic test results (including speed tests) for gateways",
    "35": "Find gateway ports overridden from template (outliers for compliance correction)",
    "36": "Check and export gateways with duplicate WAN port IP addresses (0/0/0, 0/0/1, 0/0/2)",
    "37": "Export all organization templates (gateway, network, RF, site, AP)",
    "38": "Export network template information for the organization",
    "39": "Export RF template information for the organization",
    "40": "Export AP template information for the organization",
    "41": "Export switch template information for the organization",
    "42": "Export license information for the organization",
    "43": "Export license usage information for the organization",
    "44": "Export PSK (Pre-Shared Key) information for the organization",
    "45": "Export webhook configuration for the organization",
    "46": "Export WLAN configuration for the organization",
    "47": "Export API token information for the organization",
    "48": "Export administrator information for the organization",
    "49": "Export SSO (Single Sign-On) information for the organization",
    "50": "Export MX Edge information for the organization",
    "51": "Export Organization SLE Metrics (Service Level Experience)",
    "52": "Export SLE summary metrics for all sites in the organization",
    "53": "Export Organization Insight Metrics (comprehensive operational insights)",
    "54": "Export all available const definitions from the Mist API (comprehensive endpoint coverage)",
    "55": "Export OSPF adjacency statistics for the organization",
    "56": "Export JSI PBN (Product Bulletin Notifications) data",
    "57": "Export JSI SIRT (Security Incident Response) advisories",
    "58": "Export Org WAN/Gateway Config (JSON bundle for cross-org migration)",
    "60": "Export device list for a selected site",
    "61": "Export device statistics for a selected site",
    "62": "Export port statistics for a selected site",
    "63": "Export virtual chassis information for a selected switch device",
    "64": "Export currently connected WiFi clients and session data for a selected site to SiteWiFiClients.CSV",
    "65": "Export client statistics for a selected site",
    "66": "Export beacon information for a selected site",
    "67": "Export map information for a selected site",
    "68": "Export zone information for a selected site",
    "69": "Export WLAN configuration for a selected site",
    "70": "Export OSPF adjacency statistics for a selected site",
    "71": "Export MxEdge upgrade status for a selected site",
    "72": "Export auto-map assignment status for a selected site",
    "73": "Export SLE (Service Level Experience) metrics insights for a selected site",
    "74": "Export general insight metrics for a selected site",
    "75": "Export client-specific insight metrics for a selected site",
    "76": "Export device-specific insight metrics for a selected site",
    "77": "Export Site Anomaly Events (dynamic discovery of all anomaly-related metrics from Mist API)",
    "78": "Export Site Device Anomaly Events (device-specific anomaly detection)",
    "79": "Export Site Client Anomaly Events (client-specific anomaly detection: connectivity, roaming, throughput)",
    "80": "Export site aggregate health & capacity statistics",
    "81": "Export site gateway performance metrics summary",
    "82": "Export site switch performance metrics summary",
    "83": "Export site BLE beacon statistics",
    "84": "Export site WxLAN rule usage statistics",
    "85": "Export site asset statistics",
    "86": "Export current RRM channel & power plan per AP radio",
    "87": "Export HA gateway cluster info, stats & node pair for a site",
    "88": "Export sites by AP model with site address (CSV)",
    "89": "E911 BSSID Compliance Report",
    "90": "Global Wired Client Report (operator-based MAC/MFG filtering)",
    "91": "Wired Client Manufacturer Report (exports all manufacturers)",
    "92": "Select a site (used by other functions)",
    "93": "View device inventory for a selected site",
    "94": "View statistics for a selected device at a site",
    "95": "View synthetic test stats for a selected gateway device",
    "96": "View configuration details for a selected device",
    "188": "Export all organization support tickets to CSV",
    "193": "Export all tickets with full details and comments",
    "195": "Audit site addresses from CSV (data/) - fuse Mist + SNMP + CSV hints, verify vs. web; READ-ONLY, saves report. Tier-3 browser geocoding auto-engages when available (ADDRESS_AUDIT_GEOCODE=off to skip)",
    "196": "Export async organization license-claim status summary (and optional per-device details)",
    "197": "Download client packet captures grouped by VLAN (site -> client -> VLAN -> data/packet_captures/)",
    "198": "Search Site WAN Usages (searchSiteWanUsage) - Export per-site WAN usage records to SiteWanUsages.csv",
    "199": "Search Site Webhook Deliveries (searchSiteWebhooksDeliveries) - Per site+webhook delivery audit CSV",
    "200": "Search Site Guest Authorization (searchSiteGuestAuthorization) - Per-site authorized guest CSV",
    "201": "Search Site Mist Edge Events (searchSiteMistEdgeEvents) - Per-site Mist Edge event CSV",
    "202": "Search Site NAC Client Events (searchSiteNacClientEvents) - Per-site NAC client event CSV",
    "203": "Search WAN client events for a selected site (spec 899 / issue #1407)",
    "204": "Export JSI assets and contract search results",
    "205": "Export Org Mist Edge event search results",
    "209": "Get site beacon detail by site_id + beacon_id (getSiteBeacon)",
    "210": "Export BLE beacons matching an Asset or AssetFilter for a site (getSiteAssetsOfInterest)",
    "211": "Get site asset filter detail by site_id + assetfilter_id (getSiteAssetFilter)",
    "212": "Get site asset detail by site_id + asset_id (getSiteAsset)",
    "213": "Export the application list for a selected site (getSiteApplicationList)",
    "214": "Search system events for a selected site (searchSiteSystemEvents)",
    "215": "Search alarms for a selected site (searchSiteAlarms)",
    "216": "Search tracked assets for a selected site (searchSiteAssets)",
    "217": "Search BGP peer statistics for a selected site (searchSiteBgpStats)",
    "218": "Search call quality records for a selected site (searchSiteCalls)",
    "219": "Search Sky ATP security events for a selected site (searchSiteSkyatpEvents)",
    "220": "Search wireless client events for a selected site (searchSiteWirelessClientEvents)",
    "221": "Search WAN clients for a selected site (searchSiteWanClients)",
    "222": "Search device events for a selected site (searchSiteDeviceEvents)",
    "223": "Search devices for a selected site (searchSiteDevices)",
    "224": "Search rogue access point events for a selected site (searchSiteRogueEvents)",
    "225": "Search OSPF neighbor statistics for a selected site (searchSiteOspfStats)",
    "226": "Search the last device configurations for a selected site (searchSiteDeviceLastConfigs)",
    "227": "Search device configuration history for a selected site (searchSiteDeviceConfigHistory)",
    "228": "Search discovered switches for a selected site (searchSiteDiscoveredSwitches)",
    "229": "Search zone sessions for a selected site and zone type (searchSiteZoneSessions)",
    "230": "Search wireless client sessions for the organization (searchOrgWirelessClientSessions)",
    "231": "Search wireless client events for the organization (searchOrgWirelessClientEvents)",
    "232": "Search WAN clients for the organization (searchOrgWanClients)",
    "233": "Search WAN client events for the organization (searchOrgWanClientEvents)",
    "234": "Search system events for the organization (searchOrgSystemEvents)",
    "235": "Run any org-scoped Mist count endpoint (35 operations, issue #1802)",
    "236": "Run any site-scoped Mist count endpoint (32 operations, issue #1802)",
    "237": "Run any MSP-scoped Mist count endpoint (3 operations, issue #1802)",
    "238": "Export the license entitlement, usage, and subscriptions for an MSP (listMspLicenses)",
    "240": "Export one organization security intelligence profile (getOrgSecIntelProfile)",
    "241": "Serve Mist Cloud health to a monitoring system on port 8057 (Prometheus and SNMP)",
    "242": "Find sites where an SSID is not broadcast by any AP",
    "243": "Generate the SNMP MIB from the Mist OpenAPI file and the metric catalog",
    "244": "Search service path events for a selected site (searchSiteServicePathEvents)",
    "245": "Export the Cradlepoint connection status for an organization (testOrgCradlepointConnection)",
    "246": "Troubleshoot a call for a site, client MAC, and meeting ID (troubleshootSiteCall)",
    "247": "Verify an email change token from the Mist email (verifySelfEmail)",
    "248": "Search sites for the organization (searchOrgSites)",
    "249": "Search devices for the organization (searchOrgDevices)",
    "250": "Search organization variables (searchOrgVars)",
    "251": "Search user MAC assignments for the organization (searchOrgUserMacs)",
    "252": "Search other-device events for the organization (searchOrgOtherDeviceEvents)",
    "253": "Search Mist Edges for the organization (searchOrgMxEdges)",
    "254": "Search organization inventory with optional filters (searchOrgInventory)",
    "255": "Search PSK portal logs for the organization (searchOrgPskPortalLogs)",
    "256": "Search organization webhook deliveries (searchOrgWebhooksDeliveries)",
    "257": "Search NAC clients for a selected site (searchSiteNacClients)",
    "258": "Search other-device events for a selected site (searchSiteOtherDeviceEvents)",
    "259": "Run any no-identifier Mist get or list endpoint (29 operations, issue #1807)",
    "260": "Run any org-scoped Mist get or list endpoint (55 operations, issue #1807)",
    "261": "Run any site-scoped simple Mist read endpoint (58 operations, issue #1807)",
    "262": "Run any MSP-scoped Mist get or list endpoint (10 operations, issue #1807)",
    "263": "Run any site SLE endpoint with scope prompts (17 operations, issue #1807)",
    "264": "Run any site map endpoint with map prompts (7 operations, issue #1807)",
    "265": "Run any site detail endpoint with identifier prompts (33 operations, issue #1807)",
    "266": "Run any org detail endpoint with identifier prompts (61 operations, issue #1807)",
    "267": "Run any MSP detail endpoint with identifier prompts (10 operations, issue #1807)",
    "268": "Run any remaining endpoint with identifier prompts (6 operations, issue #1807)",
    "269": "Scan the organization for rogue DHCP servers on switches (30 days, issue #2985)",
}


def build_static_menu_actions() -> dict:
    """Build a menu_actions dict with descriptions for listing only."""
    return {
        key: MenuEntry(
            menu_id=key,  # WHY: keep the static row key aligned with the real menu shape.
            handler=None,  # WHY: execution requires full MistHelper initialization.
            title=desc,  # WHY: the portal list only needs display text.
            category="static",  # WHY: the portal still reads live safety from OperationRegistry.
            destructive=False,  # WHY: static rows cannot execute destructive code.
            supports_fast=False,  # WHY: static rows never run in the systematic test runner.
        )
        for key, desc in MENU_DESCRIPTIONS.items()
    }
