"""Static menu operation descriptions for the web portal.

Provides operation metadata without requiring MistHelper imports
or API authentication. Used by wsgi.py to populate the operations
list when the portal starts independently from MistHelper CLI.

Warning: this file is generated. Run
``python scripts/generate_portal_menu_registry.py`` after adding or renaming an
operation. ``tests/guardrails/test_portal_menu_registry_sync.py`` fails when
this map drifts from ``OperationRegistry``.

The map holds every operation that ``OperationRegistry`` calls ``safe`` or
``interactive_safe``, because those are the two classes the portal may run.
"""

from src.utils.menu_entry import MenuEntry  # WHY: static rows must match the real menu row shape.

MENU_DESCRIPTIONS = {
    "0": "Exit MistHelper",
    "1": "Export a list of all sites in the organization",
    "2": "Export a list of sites with location and timezone info",
    "3": "Export all sites using the 'list' sites API endpoint (to SiteList_ListAPI.csv, only if not already present)",
    "4": "Export all current guest users and last 7 days of historical guests to CSV",
    "5": "Export E911 report for the organization",
    "6": "Site Config Analysis - Scan all sites for zone, engagement dwell tag, and occupancy setting deviations",
    "7": "Site Inventory Health Analysis - Find sites with APs missing switches/gateways, or with offline infrastructure",
    "8": "Export the full inventory of devices in the organization",
    "9": "Export a list of all devices in the organization",
    "10": "Export a list of all devices with associated site and address info",
    "11": "Export a list of gateways with associated site and address info",
    "12": "Export combined inventory with site and address info by calendar week",
    "13": "Export org device model counts, firmware version distribution, and versions per model (MSP-aware)",
    "14": "Check virtual chassis to virtual MAC conversion status for all switches",
    "15": "Export statistics for all devices in the organization",
    "16": "Export VPN peer path statistics for the organization",
    "17": "Export all switch virtual chassis (VC/stacking) stats to CSV",
    "18": "Export detailed device statistics for all gateways (with freshness check)",
    "19": "Export port-level statistics for switches and gateways",
    "20": "Export all organization alarms from the past day",
    "21": "Export all device events from the past 24 hours",
    "22": "Export audit logs for the organization (last 24 hours)",
    "23": "Export self (admin account) audit log",
    "24": "Export security events for the organization",
    "25": "Audit Log Analysis - Mermaid timeline + interactive HTML report",
    "26": "Offline Device Report",
    "27": "Export wireless client statistics for the organization",
    "28": "Export wired client statistics for the organization",
    "29": "Export rogue client detections for the organization",
    "30": "Export rogue AP detections for the organization",
    "31": "Export gateway management overlay IPs grouped by template association",
    "32": "Export gateway templates from the organization",
    "33": "Export synthetic test results for all gateways",
    "34": "Export all synthetic test results (including speed tests) for gateways",
    "35": "Find gateway ports overridden from template (outliers for compliance correction)",
    "36": "Check and export gateways with duplicate WAN port IP addresses (0/0/0, 0/0/1, 0/0/2)",
    "37": "Export all organization templates (gateway, network, RF, site, AP)",
    "38": "Export network template information for the organization",
    "39": "Export RF template information for the organization",
    "40": "Export AP template information for the organization",
    "41": "Export switch template information for the organization",
    "42": "Export license information for the organization",
    "43": "Export license usage information for the organization",
    "44": "Export PSK (Pre-Shared Key) information for the organization",
    "45": "Export webhook configuration for the organization",
    "46": "Export WLAN configuration for the organization",
    "47": "Export API token information for the organization",
    "48": "Export administrator information for the organization",
    "49": "Export SSO (Single Sign-On) information for the organization",
    "50": "Export MX Edge information for the organization",
    "51": "Export Organization SLE Metrics (Service Level Experience)",
    "52": "Export SLE summary metrics for all sites in the organization",
    "53": "Export Organization Insight Metrics (comprehensive operational insights)",
    "54": "Export all available const definitions from the Mist API (comprehensive endpoint coverage)",
    "55": "Export OSPF adjacency statistics for the organization",
    "56": "Export JSI PBN (Product Bulletin Notifications) data",
    "57": "Export JSI SIRT (Security Incident Response) advisories",
    "58": "Export Org WAN/Gateway Config (JSON bundle for cross-org migration)",
    "59": "Export configuration settings for all sites",
    "60": "Export device list for a selected site",
    "61": "Export device statistics for a selected site",
    "62": "Export port statistics for a selected site",
    "63": "Export virtual chassis information for a selected switch device",
    "64": "Export currently connected WiFi clients and session data for a selected site to SiteWiFiClients.CSV",
    "65": "Export client statistics for a selected site",
    "66": "Export beacon information for a selected site",
    "67": "Export map information for a selected site",
    "68": "Export zone information for a selected site",
    "69": "Export WLAN configuration for a selected site",
    "70": "Export OSPF adjacency statistics for a selected site",
    "71": "Export MxEdge upgrade status for a selected site",
    "72": "Export auto-map assignment status for a selected site",
    "73": "Export SLE (Service Level Experience) metrics insights for a selected site",
    "74": "Export general insight metrics for a selected site",
    "75": "Export client-specific insight metrics for a selected site",
    "76": "Export device-specific insight metrics for a selected site",
    "77": "Export Site Anomaly Events (dynamic discovery of all anomaly-related metrics from Mist API)",
    "78": "Export Site Device Anomaly Events (device-specific anomaly detection)",
    "79": "Export Site Client Anomaly Events (client-specific anomaly detection: connectivity, roaming, throughput)",
    "80": "Export site aggregate health & capacity statistics",
    "81": "Export site gateway performance metrics summary",
    "82": "Export site switch performance metrics summary",
    "83": "Export site BLE beacon statistics",
    "84": "Export site WxLAN rule usage statistics",
    "85": "Export site asset statistics",
    "86": "Export current RRM channel & power plan per AP radio",
    "87": "Export HA gateway cluster info, stats & node pair for a site",
    "88": "Export sites by AP model with site address (CSV)",
    "89": "E911 BSSID Compliance Report",
    "90": "Global Wired Client Report (operator-based MAC/MFG filtering)",
    "91": "Wired Client Manufacturer Report (browse & select)",
    "92": "Select a site (used by other functions)",
    "93": "View device inventory for a selected site",
    "94": "View statistics for a selected device at a site",
    "95": "View synthetic test stats for a selected gateway device",
    "96": "View configuration details for a selected device",
    "97": "Export all org device events from the last 52 weeks (streaming with checkpoint/resume)",
    "98": "Export ALL audit logs for the organization (last 52 weeks)",
    "99": "Export configuration details for all gateway devices across all sites",
    "100": "Process and merge CSV files of SFP Module locations into a single CSV file",
    "101": "Generate support package for each site",
    "102": "Show MAC table on switch device via WebSocket (Layer 2 switching table)",
    "103": "Show forwarding table on gateway device via WebSocket (Layer 3 routing table)",
    "104": "Show routing table on switches via WebSocket (Switch L3 routing - BGP/OSPF/Static)",
    "105": "Show SSR/SRX routing table via dedicated API (128T/SRX gateways - Advanced BGP analysis)",
    "106": "Show OSPF Neighbors on SSR/SRX Gateway",
    "107": "Show OSPF Interfaces on SSR/SRX Gateway",
    "108": "Show OSPF Database on SSR/SRX Gateway",
    "109": "Show OSPF Summary on SSR/SRX Gateway",
    "110": "Show Sessions on SSR/SRX Gateway",
    "111": "Show Service Path on SSR Gateway",
    "112": "Show BGP Summary on Switch or Gateway",
    "113": "Show ARP Table on Switch or Gateway",
    "114": "Show DHCP Leases on Switch or Gateway",
    "115": "Show 802.1X Table on Switch",
    "116": "Show EVPN Database on Switch or Gateway",
    "117": "Test DNS Resolution on SSR Gateway",
    "118": "WebSocket Device Ping - Execute ping command on device via WebSocket stream (real-time output)",
    "119": "WebSocket Device ARP - Execute ARP command on device via WebSocket stream (real-time output)",
    "120": "WebSocket Service Ping - Execute service-specific ping on SSR gateways via WebSocket stream (real-time output)",
    "121": "Run ARP command on an AP and receive output via WebSocket",
    "122": "Cable Test on Switch Port",
    "123": "Traceroute from device to destination host (AP/Switch/Gateway)",
    "124": "Monitor Traffic on Switch/SRX Port (streaming, Ctrl+C to stop)",
    "125": "Run Top Command on Switch/SRX (streaming, Ctrl+C to stop)",
    "126": "Poll Fresh Statistics from Switch",
    "127": "Create Device Snapshot on Switch",
    "128": "Locate Device - Blink LED on AP or Switch",
    "129": "Unlocate Device - Stop LED Blinking on AP or Switch",
    "130": "Re-adopt Switch Device",
    "131": "Get ZTP Password for Switch/Gateway (console only)",
    "132": "Get Config CLI Commands for Switch Adoption",
    "133": "Upload Support File from Switch/Gateway",
    "134": "Start Site Packet Capture - Wireless/Wired/Gateway/Scan captures with WebSocket streaming",
    "135": "Start Organization Packet Capture - MxEdge captures for org-level Mist Edges only",
    "136": "MSP (Managed Service Provider) info - Displays guidance only (MSP data requires MSP-level API access, not org-level)",
    "137": "Check current firmware upgrade status across organization with detailed progress monitoring and export to CSV",
    "138": "Compare inventory data with external CSV file using configurable address similarity threshold (ADDRESS_MATCH_THRESHOLD in .env)",
    "139": "Interactive Marvis (VNA) AI troubleshooting - guided client, device, and network analysis",
    "140": "Interactively execute a CLI command on a gateway or switch (exit with ~)",
    "141": "Launch Terminal User Interface (TUI) mode - Visual navigation of Mist API library with interactive exploration",
    "142": "Maps Manager - Interactive site floorplan and map operations (sub-menu)",
    "143": "Switch to interactive login (email/password) - Enables MSP-level API access for current session",
    "144": "MSP Inventory Export - Export device inventory across all MSPs and all organizations to CSV (requires MSP privileges via --login)",
    "145": "SSID Template Consolidation (5-Phase Guided Workflow)",
    "146": "WAN Hub Group Number Manager",
    "147": "WAN Hub-Spoke VPN Builder",
    "148": "Manage WLAN RADIUS Authentication Timers - Configure auth_servers_timeout, auth_servers_retries, auth_server_selection, and fast_dot1x_timers for site or template WLANs",
    "149": "Set WAN2 Interface Site Variable - Configure 'wan2_interface' site variable for template-based WAN migration (Reports sites with ge-0/0/1 overrides)",
    "150": "Extract Gateway Template Configuration (DIA_Pico, Picocell) - Save specific configs to JSON for replication",
    "151": "Loop refresh of core datasets (site list, inventory, stats, ports, VPN) Stop with CTRL+C or create 'stop_loop.txt'",
    "153": "Bulk Org Data Collection (populate ArangoDB/Redis/SQLite with all org-level APIs)",
    "154": "DESTRUCTIVE: Advanced AP firmware upgrade with mode selection - upgrade by site list/selection or by Gateway Template assignment",
    "155": "DESTRUCTIVE: Advanced Switch firmware upgrade with mode selection - upgrade by site list/selection or by Gateway Template assignment",
    "156": "DESTRUCTIVE: Advanced SSR firmware upgrade with mode selection - upgrade by site list/selection or by Gateway Template assignment",
    "157": "DESTRUCTIVE: Org-Level AP Firmware Upgrade - Efficient multi-site upgrade using org-level API (1 call per version vs 1 per site), MSP multi-org support, supports --dry-run",
    "158": "DESTRUCTIVE: Reboot all devices associated with templates listed in GatewayTemplateRebootList.CSV and log results",
    "159": " Bounce Switch/Gateway Port (y/N confirmation)",
    "160": " Reprovision Switch/Gateway (y/N confirmation)",
    "161": " DESTRUCTIVE: Convert a virtual chassis switch to virtual MAC (interactive, supports --dry-run)",
    "162": " DESTRUCTIVE: Convert all virtual chassis switches in sites listed in VCConvert.CSV (bulk operation)",
    "163": "DESTRUCTIVE: Update Gateway Templates to Use WAN2 Variable - Replace hardcoded 'ge-0/0/1' references with {{wan2_interface}} variable (Requires uppercase 'MIGRATE' confirmation, supports --dry-run)",
    "164": "DESTRUCTIVE: Apply Gateway Template Configuration - Replicate extracted configs to other templates (Requires uppercase 'APPLY' confirmation)",
    "165": "DESTRUCTIVE: Clone Gateway Template by State and Country - Create state/country-specific templates and assign sites (Requires uppercase 'CLONE' confirmation)",
    "166": "DESTRUCTIVE: Configure WAN Probe Override on Gateway Templates - Set ICMP probe IPs and profile for all WAN interfaces (Requires uppercase 'APPLY' confirmation, supports --dry-run)",
    "167": "DESTRUCTIVE: Configure WAN Probe on Device Port Overrides - Set ICMP probe on device-level WAN overrides only (Requires uppercase 'APPLY' confirmation, supports --dry-run)",
    "168": "Site Auto-Upgrade Configuration - Configure AP auto-upgrade settings for sites with MSP multi-org support (supports --dry-run)",
    "169": "DESTRUCTIVE: Site Analytics Configuration - Apply standard RTSA/Rogue/Engagement/Occupancy settings to deviating sites",
    "170": "Bulk RADIUS WLAN Configuration - Configure auth_servers_timeout, auth_servers_retries, fast_dot1x_timers for org-level RADIUS WLANs",
    "171": "DESTRUCTIVE: Create 137 test sites from NorthAmericanTestSites.csv - Real landmarks across 13 North American countries (Requires uppercase 'CREATE' confirmation)",
    "172": "DESTRUCTIVE: Create country-specific RF templates and assign sites to matching templates (Requires uppercase 'CREATE' confirmation)",
    "173": "DESTRUCTIVE: Scan org for AP models and create Device Profile per model with inherit/auto settings (Requires uppercase 'CREATE' confirmation)",
    "174": "DESTRUCTIVE: Assign APs to Device Profiles matching their model type (AP-{model}) - Skips APs without matching profiles (Requires uppercase 'ASSIGN' confirmation)",
    "175": "Enhanced SSH Command Runner - Execute commands on remote network devices via SSH",
    "176": "SSH Runner - Target gateways by template name (online gateways with management IPs only)",
    "177": " DESTRUCTIVE: Clear ARP Cache (type CLEAR)",
    "178": " DESTRUCTIVE: Clear BGP Routes (type CLEAR)",
    "179": " DESTRUCTIVE: Clear Session on SSR/SRX (type CLEAR)",
    "180": " DESTRUCTIVE: Clear MAC Table (type CLEAR)",
    "181": " DESTRUCTIVE: Clear BPDU Errors on Switch (type CLEAR)",
    "182": " DESTRUCTIVE: Clear Learned MACs from Switch Port (type CLEAR)",
    "183": " DESTRUCTIVE: Clear Policy Hit Count on SSR (type CLEAR)",
    "184": " Release DHCP Lease on Switch/Gateway (y/N)",
    "185": " Release DHCP Lease on SSR/SRX (y/N)",
    "186": "Clear CSV Cache Files (delete all generated cache CSVs)",
    "187": "Import Org WAN/Gateway Config (cross-org migration with conflict detection)",
    "188": "Export all organization support tickets to CSV",
    "189": "Create a new organization support ticket",
    "190": "Add a comment (with optional file attachment) to a support ticket",
    "191": "Update fields on an existing support ticket",
    "192": "View a support ticket with full comments and history",
    "193": "Export all tickets with full details and comments",
    "194": " DESTRUCTIVE: Clone Device Config to Gateway Template - Select a gateway, extract its local config, and create a new org gateway template (Requires typing 'CREATE' to confirm)",
    "195": "Audit site addresses from CSV (data/) - fuse Mist + SNMP + CSV hints, verify vs. web; READ-ONLY, saves report. Tier-3 browser geocoding auto-engages when available (ADDRESS_AUDIT_GEOCODE=off to skip)",
    "196": "Export async organization license-claim status summary (and optional per-device details)",
    "197": "Download client packet captures grouped by VLAN (site -> client -> VLAN -> data/packet_captures/)",
    "198": "Search Site WAN Usages (searchSiteWanUsage) - Export per-site WAN usage records to SiteWanUsages.csv",
    "199": "Search Site Webhook Deliveries (searchSiteWebhooksDeliveries) - Per site+webhook delivery audit CSV",
    "200": "Search Site Guest Authorization (searchSiteGuestAuthorization) - Per-site authorized guest CSV",
    "201": "Search Site Mist Edge Events (searchSiteMistEdgeEvents) - Per-site Mist Edge event CSV",
    "202": "Search Site NAC Client Events (searchSiteNacClientEvents) - Per-site NAC client event CSV",
    "203": "Search WAN client events for a selected site",
    "204": "Export JSI assets and contract search results",
    "205": "Export Org Mist Edge event search results",
    "206": " DESTRUCTIVE: Manage org Zscaler synthetic probes - Build/merge/swap synthetic_test.custom_probes from curated Zscaler catalogue",
    "207": " DESTRUCTIVE: Migrate APs between device profiles - Reassign every AP bound to a source device profile to a chosen target profile (Requires typing 'MIGRATE' or 'DRY-RUN' to confirm)",
    "208": " DESTRUCTIVE: Revert an AP profile migration from a backup file - Reassign each listed AP back to its original device profile (Requires typing 'REVERT' to confirm)",
    "209": "Get site beacon detail by site_id + beacon_id (getSiteBeacon)",
    "210": "Export BLE beacons matching an Asset or AssetFilter for a site (getSiteAssetsOfInterest)",
    "211": "Get site asset filter detail by site_id + assetfilter_id (getSiteAssetFilter)",
    "212": "Get site asset detail by site_id + asset_id (getSiteAsset)",
    "213": "Export the application list for a selected site (getSiteApplicationList)",
    "214": "Search system events for a selected site (searchSiteSystemEvents)",
    "215": "Search alarms for a selected site (searchSiteAlarms)",
    "216": "Search tracked assets for a selected site (searchSiteAssets)",
    "217": "Search BGP peer statistics for a selected site (searchSiteBgpStats)",
    "218": "Search call quality records for a selected site (searchSiteCalls)",
    "219": "Search Sky ATP security events for a selected site (searchSiteSkyatpEvents)",
    "220": "Search wireless client events for a selected site (searchSiteWirelessClientEvents)",
    "221": "Search WAN clients for a selected site (searchSiteWanClients)",
    "222": "Search device events for a selected site (searchSiteDeviceEvents)",
    "223": "Search devices for a selected site (searchSiteDevices)",
    "224": "Search rogue access point events for a selected site (searchSiteRogueEvents)",
    "225": "Search OSPF neighbor statistics for a selected site (searchSiteOspfStats)",
    "226": "Search the last device configurations for a selected site (searchSiteDeviceLastConfigs)",
    "227": "Search device configuration history for a selected site (searchSiteDeviceConfigHistory)",
    "228": "Search discovered switches for a selected site (searchSiteDiscoveredSwitches)",
    "229": "Search zone sessions for a selected site and zone type (searchSiteZoneSessions)",
    "230": "Search wireless client sessions for the organization (searchOrgWirelessClientSessions)",
    "231": "Search wireless client events for the organization (searchOrgWirelessClientEvents)",
    "232": "Search WAN clients for the organization (searchOrgWanClients)",
    "233": "Search WAN client events for the organization (searchOrgWanClientEvents)",
    "234": "Search system events for the organization (searchOrgSystemEvents)",
    "235": "Run any org-scoped Mist count endpoint (35 operations)",
    "236": "Run any site-scoped Mist count endpoint (33 operations)",
    "237": "Run any MSP-scoped Mist count endpoint (3 operations)",
    "238": "Export the license entitlement, usage, and subscriptions for an MSP (listMspLicenses)",
    "239": "Launch the upgrade capture portal on port 8056 (pre-check, upgrade, post-check)",
    "240": "Export one organization security intelligence profile (getOrgSecIntelProfile)",
    "241": "Serve Mist Cloud health to a monitoring system on port 8057 (Prometheus and SNMP)",
    "242": "Find sites where an SSID is not broadcast by any AP",
    "243": "Generate the SNMP MIB from the Mist OpenAPI file and the metric catalog",
    "244": "Search service path events for a selected site (searchSiteServicePathEvents)",
    "245": "Export the Cradlepoint connection status for an organization (testOrgCradlepointConnection)",
    "246": "Troubleshoot a call for a site, client MAC, and meeting ID (troubleshootSiteCall)",
    "247": "Verify an email change token from the Mist email (verifySelfEmail)",
    "248": "Search sites for the organization (searchOrgSites)",
    "249": "Search devices for the organization (searchOrgDevices)",
    "250": "Search organization variables (searchOrgVars)",
    "251": "Search user MAC assignments for the organization (searchOrgUserMacs)",
    "252": "Search other-device events for the organization (searchOrgOtherDeviceEvents)",
    "253": "Search Mist Edges for the organization (searchOrgMxEdges)",
    "254": "Search organization inventory with optional filters (searchOrgInventory)",
    "255": "Search PSK portal logs for the organization (searchOrgPskPortalLogs)",
    "256": "Search organization webhook deliveries (searchOrgWebhooksDeliveries)",
    "257": "Search NAC clients for a selected site (searchSiteNacClients)",
    "258": "Search other-device events for a selected site (searchSiteOtherDeviceEvents)",
    "259": "Run any no-identifier Mist get or list endpoint (29 operations)",
    "260": "Run any org-scoped Mist get or list endpoint (55 operations)",
    "261": "Run any site-scoped simple Mist read endpoint (58 operations)",
    "262": "Run any MSP-scoped Mist get or list endpoint (10 operations)",
    "263": "Run any site SLE endpoint with scope prompts (17 operations)",
    "264": "Run any site map endpoint with map prompts (7 operations)",
    "265": "Run any site detail endpoint with identifier prompts (33 operations)",
    "266": "Run any org detail endpoint with identifier prompts (61 operations)",
    "267": "Run any MSP detail endpoint with identifier prompts (10 operations)",
    "268": "Run any remaining endpoint with identifier prompts (6 operations)",
    "269": "Scan the organization for rogue DHCP servers on switches (30 days)",
    "270": "Export or resolve Marvis Actions by category and subcategory",
    "271": "Export the subscription and contract expiry report",
    "272": "Export the certificate expiry report",
    "273": "Admin and API Token Hygiene Report",
    "274": "Export the PSK hygiene report",
    "275": "Audit site variable coverage",
    "276": "Export the organization security posture checklist",
    "277": "Export the organization switch scorecard",
    "278": "Export the organization access point scorecard",
    "279": "Organization WAN Edge Scorecard",
    "282": "Export the rogue and PCI evidence pack",
    "283": "Trigger a synthetic test on demand",
    "284": "Test the guest portal SMS provider",
    "285": "Validate a NAC identity provider credential",
    "288": "Show the SSR registration commands",
    "289": "Export the client fingerprint census for a site",
    "290": "Run spectrum analysis and RF diagnostic recording",
}


def build_static_menu_actions() -> dict:
    """Build a menu_actions dict with descriptions for listing only."""
    return {
        key: MenuEntry(
            menu_id=key,  # WHY: keep the static row key aligned with the real menu shape.
            handler=None,  # WHY: execution requires full MistHelper initialization.
            title=desc,  # WHY: the portal list only needs display text.
            category="static",  # WHY: the portal still reads live safety from OperationRegistry.
            destructive=False,  # WHY: static rows cannot execute destructive code.
            supports_fast=False,  # WHY: static rows never run in the systematic test runner.
        )
        for key, desc in MENU_DESCRIPTIONS.items()
    }
