"""ENDPOINT_PRIMARY_KEY_STRATEGIES extracted from MistHelper (initiative 1015, T-04).

Owns the ``ENDPOINT_PRIMARY_KEY_STRATEGIES`` module-level dict originally
defined at MistHelper.py:2965 (spanning 2327 lines). The dict maps API
function names (getOrgInventory, listOrgSites, listSiteDevices, ...) to
per-endpoint primary-key extraction strategies used by the data-processing
pipeline in ``src/db/database_schema_utils.py`` when generating SQLite/Redis
schemas and upsert plans.

Two callsite classes are rewritten in the same PR:

1. Direct import (MistHelper.py:5678) -- the ``strategies=`` kwarg passed
   into the database schema generation pipeline now flows through
   ``from src.refactors.endpoint_primary_key_strategies import
   ENDPOINT_PRIMARY_KEY_STRATEGIES``.
2. Lazy-module bypass (src/db/database_schema_utils.py:66-77) -- the
   ``mh.ENDPOINT_PRIMARY_KEY_STRATEGIES`` lookups previously resolved via
   ``importlib.import_module("MistHelper")`` continue to work because
   MistHelper.py re-imports the symbol at the top of the file, preserving
   the ``mh.ENDPOINT_PRIMARY_KEY_STRATEGIES`` attribute for existing
   dynamic-import consumers without a facade class.

Bare module-level dict per spec: no wrapper class, no facade, no shim.
The analyzer's ``EndpointPrimaryKeyStrategiesManager`` naming hint is
intentionally ignored -- this is a data catalog, not behavior.

Strategy schema (each value): {
    "type": "natural_pk" | "composite_pk" | "auto_pk" | "time_series",
    "primary_key": [column_names],
    "indexes": [column_names],
    "unique_constraints": [column_names],
    "description": human-readable one-liner,
}
"""

# This configuration determines how each API endpoint's data should be stored in Redis/SQLite
# with proper primary keys to eliminate artificial api_id fields and enable efficient queries
ENDPOINT_PRIMARY_KEY_STRATEGIES = {
    # Type 1: Natural primary key using API id field (for entity APIs)
    # These APIs return objects with stable UUID identifiers that make perfect primary keys
    "getOrgInventory": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "mac", "serial", "model", "type"],
        "unique_constraints": [],
        "description": "Organization device inventory with stable UUID identifiers",
    },
    "listOrgSites": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "country_code", "address"],
        "unique_constraints": [],
        "description": "Organization sites with stable UUID identifiers",
    },
    "listSiteDevices": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "mac", "serial", "model", "type", "name"],
        "unique_constraints": [],
        "description": "Site devices with stable UUID identifiers",
    },
    "getOrgDevices": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "mac", "serial", "model", "type"],
        "unique_constraints": [],
        "description": "Organization devices with stable UUID identifiers",
    },
    # Template and configuration entities
    "createOrgGatewayTemplate": {
        "type": "natural_pk",  # API returns a UUID id field on the newly created template
        "primary_key": ["id"],  # Template UUID is the stable natural key for upsert
        "indexes": ["org_id", "name", "type"],  # Secondary lookup fields for queries
        "unique_constraints": [],  # No additional unique constraints beyond PK
        "description": "Newly created org gateway template from device config clone",
    },
    "listOrgGatewayTemplates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "type"],
        "unique_constraints": [],
        "description": "Gateway templates with stable UUID identifiers",
    },
    "listOrgNetworkTemplates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Network templates with stable UUID identifiers",
    },
    "listOrgRfTemplates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "band"],
        "unique_constraints": [],
        "description": "RF templates with stable UUID identifiers",
    },
    "listOrgSiteTemplates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Site templates with stable UUID identifiers",
    },
    "listOrgAptemplates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "AP templates with stable UUID identifiers",
    },
    "listOrgSecPolicies": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Security policies with stable UUID identifiers",
    },
    "listOrgPsks": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "ssid"],
        "unique_constraints": [],
        "description": "Pre-shared keys with stable UUID identifiers",
    },
    "listOrgWebhooks": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "type"],
        "unique_constraints": [],
        "description": "Webhooks with stable UUID identifiers",
    },
    # Type 2: Composite primary key for event and log APIs
    # These APIs return time-series data that requires composite keys for uniqueness
    "searchOrgAlarms": {
        "type": "composite_pk",
        "primary_key": ["id", "org_id", "timestamp"],
        "indexes": ["org_id", "timestamp", "severity", "type", "site_id"],
        "unique_constraints": [],
        "description": "Organization alarms with composite key for time-series data",
    },
    "searchOrgDeviceEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "device_id", "timestamp"],
        "indexes": ["device_id", "timestamp", "type", "org_id", "site_id"],
        "unique_constraints": [],
        "description": "Device events with composite key for uniqueness",
    },
    "searchOrgClientEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "site_id", "timestamp"],
        "indexes": ["site_id", "timestamp", "type", "client_mac", "device_id"],
        "unique_constraints": [],
        "description": "Client events with composite key for uniqueness",
    },
    "searchOrgSystemEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "org_id", "timestamp"],
        "indexes": ["org_id", "timestamp", "type"],
        "unique_constraints": [],
        "description": "System events with composite key for uniqueness",
    },
    # Type 3: TimeSeries metrics -- pure-numeric endpoints routed to Redis TimeSeries
    # These APIs return time-series data with explicit numeric and label fields
    "listOrgDevicesStats": {
        "type": "timeseries_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["device_id", "timestamp", "org_id", "site_id", "type"],
        "unique_constraints": [],
        "description": "Organization device statistics routed to Redis TimeSeries",
        "ts_value_fields": ["cpu_util", "mem_util", "uptime", "num_clients"],
        "ts_label_fields": ["hostname", "model", "type", "site_id"],
    },
    "listSiteDevicesStats": {
        "type": "timeseries_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["device_id", "timestamp", "site_id", "type"],
        "unique_constraints": [],
        "description": "Site device statistics routed to Redis TimeSeries",
        "ts_value_fields": ["cpu_util", "mem_util", "uptime", "num_clients"],
        "ts_label_fields": ["hostname", "model", "type"],
    },
    "listSiteWirelessClientsStats": {
        "type": "timeseries_pk",
        "primary_key": ["client_mac", "timestamp"],
        "indexes": ["client_mac", "timestamp", "site_id", "device_id"],
        "unique_constraints": [],
        "description": "Wireless client statistics routed to Redis TimeSeries",
        "ts_value_fields": ["rssi", "snr", "rx_rate", "tx_rate"],
        "ts_label_fields": ["ssid", "hostname", "device_id"],
    },
    "searchOrgSwOrGwPorts": {
        "type": "timeseries_pk",
        "primary_key": ["device_id", "port_id", "timestamp"],
        "indexes": ["device_id", "port_id", "timestamp", "org_id"],
        "unique_constraints": [],
        "description": "Switch/gateway port statistics routed to Redis TimeSeries",
        "ts_value_fields": ["rx_bytes", "tx_bytes", "rx_errors", "tx_errors"],
        "ts_label_fields": ["port_id", "device_id", "org_id"],
    },
    "searchSiteSwOrGwPorts": {
        "type": "timeseries_pk",
        "primary_key": ["device_id", "port_id", "timestamp"],
        "indexes": ["device_id", "port_id", "timestamp", "site_id"],
        "unique_constraints": [],
        "description": "Site port statistics routed to Redis TimeSeries",
        "ts_value_fields": ["rx_bytes", "tx_bytes", "rx_errors", "tx_errors"],
        "ts_label_fields": ["port_id", "device_id", "site_id"],
    },
    "searchOrgPeerPathStats": {
        "type": "timeseries_pk",
        "primary_key": ["from_device", "to_device", "timestamp"],
        "indexes": ["from_device", "to_device", "timestamp", "org_id"],
        "unique_constraints": [],
        "description": "Peer path statistics routed to Redis TimeSeries",
        "ts_value_fields": ["latency", "jitter", "loss"],
        "ts_label_fields": ["from_device", "to_device", "org_id"],
    },
    # -- Issue #177: Site routing / network topology endpoints --
    "searchSiteBgpStats": {
        "type": "composite_pk",
        "primary_key": ["mac", "neighbor", "timestamp"],
        "indexes": ["site_id", "org_id", "state", "neighbor_as"],
        "unique_constraints": [],
        "description": "Site BGP peering statistics",
    },
    "searchSiteOspfStats": {
        "type": "composite_pk",
        "primary_key": ["mac", "peer_ip", "timestamp"],
        "indexes": ["site_id", "org_id", "state", "port_id"],
        "unique_constraints": [],
        "description": "Site OSPF adjacency statistics",
    },
    "listSiteEvpnTopologies": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "name"],
        "unique_constraints": [],
        "description": "Site EVPN topology definitions",
    },
    "searchSiteDiscoveredSwitches": {
        "type": "composite_pk",
        "primary_key": ["system_name", "mgmt_addr", "timestamp"],
        "indexes": ["site_id", "org_id", "vendor", "model"],
        "unique_constraints": [],
        "description": "Site discovered (unadopted) switches",
    },
    "listSiteDiscoveredSwitchesMetrics": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["site_id", "org_id"],
        "unique_constraints": [],
        "description": "Site discovered switch aggregate metrics",
    },
    "searchSiteDiscoveredSwitchesMetrics": {
        "type": "composite_pk",
        "primary_key": ["system_name", "type", "timestamp"],
        "indexes": ["site_id", "org_id", "scope", "score"],
        "unique_constraints": [],
        "description": "Site discovered switch metric search results",
    },
    "listSiteCurrentRrmNeighbors": {
        "type": "composite_pk",
        "primary_key": ["mac"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Site RRM AP neighbor relationships",
    },
    # Map-related endpoints
    "listSiteMaps": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "name", "type", "created_time", "modified_time"],
        "unique_constraints": [],
        "description": "Site maps with stable UUID identifiers",
    },
    "getSiteMap": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "name", "type"],
        "unique_constraints": [],
        "description": "Individual site map with stable UUID identifier",
    },
    "listSiteMapStacks": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "name", "created_time", "modified_time"],
        "unique_constraints": [],
        "description": "Site map stacks (multi-floor groupings)",
    },
    # Zone and RSSI zone endpoints
    "listSiteZones": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "map_id", "name"],
        "unique_constraints": [],
        "description": "Zones defined on site maps",
    },
    "listSiteZonesStats": {
        "type": "composite_pk",
        "primary_key": ["id", "map_id"],
        "indexes": ["site_id", "map_id", "name", "num_clients"],
        "unique_constraints": [],
        "description": "Zone statistics with client counts",
    },
    "listSiteRssiZones": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "name"],
        "unique_constraints": [],
        "description": "RSSI-based zones for location analytics",
    },
    "listSiteRssiZonesStats": {
        "type": "composite_pk",
        "primary_key": ["id", "map_id"],
        "indexes": ["site_id", "map_id", "name"],
        "unique_constraints": [],
        "description": "RSSI zone statistics",
    },
    # Beacon endpoints
    "listSiteBeacons": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "map_id", "name", "type"],
        "unique_constraints": [],
        "description": "BLE beacons deployed on site maps",
    },
    "listSiteVBeacons": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "map_id", "name"],
        "unique_constraints": [],
        "description": "Virtual BLE beacons on site maps",
    },
    # Zone session search
    "searchSiteZoneSessions": {
        "type": "composite_pk",
        "primary_key": ["zone_id", "mac", "enter"],
        "indexes": ["site_id", "map_id", "zone_id", "mac", "enter", "exit"],
        "unique_constraints": [],
        "description": "Client zone session events for location analytics",
    },
    # -- Issue #174: Site events & alarms --
    "searchSiteAlarms": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["site_id", "type", "severity"],
        "unique_constraints": [],
        "description": "Site alarm search results",
    },
    "searchSiteDeviceEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["site_id", "device_type", "type", "mac"],
        "unique_constraints": [],
        "description": "Site device event search results",
    },
    "searchSiteSystemEvents": {
        "type": "composite_pk",
        "primary_key": ["type", "timestamp"],
        "indexes": ["site_id", "type"],
        "unique_constraints": [],
        "description": "Site system event search results",
    },
    "searchSiteOtherDeviceEvents": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["site_id", "mac", "type"],
        "unique_constraints": [],
        "description": "Site other device event search results",
    },
    "searchSiteSkyatpEvents": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["site_id", "mac", "type"],
        "unique_constraints": [],
        "description": "Site Sky ATP event search results",
    },
    "searchSiteServicePathEvents": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["site_id", "mac", "type", "vpn_name"],
        "unique_constraints": [],
        "description": "Site WAN service path event search results",
    },
    "listSiteRoamingEvents": {
        "type": "composite_pk",
        "primary_key": ["client_mac", "timestamp"],
        "indexes": ["site_id", "client_mac", "ap"],
        "unique_constraints": [],
        "description": "Site client roaming events",
    },
    "listSiteRrmEvents": {
        "type": "composite_pk",
        "primary_key": ["ap_id", "timestamp"],
        "indexes": ["site_id", "ap_id", "band"],
        "unique_constraints": [],
        "description": "Site radio resource management events",
    },
    "listSiteAnomalyEvents": {
        "type": "composite_pk",
        "primary_key": ["timestamp"],
        "indexes": ["site_id", "metric"],
        "unique_constraints": [],
        "description": "Site anomaly detection events",
    },
    # Type 3b: Config history, synthetic tests, webhook deliveries, packet captures
    "searchSiteDeviceConfigHistory": {
        "type": "composite_pk",
        "primary_key": ["timestamp"],
        "indexes": ["site_id", "version", "channel_24", "channel_5"],
        "unique_constraints": [],
        "description": "Site device config change history",
    },
    "searchSiteDeviceLastConfigs": {
        "type": "composite_pk",
        "primary_key": ["timestamp"],
        "indexes": ["site_id", "version", "channel_24", "channel_5"],
        "unique_constraints": [],
        "description": "Site device last known configurations",
    },
    "searchSiteSyntheticTest": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["site_id", "mac", "type", "status", "port_id"],
        "unique_constraints": [],
        "description": "Site synthetic test results",
    },
    "searchSiteWebhooksDeliveries": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["site_id", "org_id", "webhook_id", "status", "topic"],
        "unique_constraints": [],
        "description": "Site webhook delivery audit records",
    },
    "listSitePacketCaptures": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "type", "timestamp"],
        "unique_constraints": [],
        "description": "Site packet capture metadata",
    },
    # Issue #173: Site-level WLANs, PSKs, Webhooks, WxLAN policies
    "listSiteWlans": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "ssid", "template_id"],
        "unique_constraints": [],
        "description": "Site-level WLAN configurations",
    },
    "listSitePsks": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "ssid", "name"],
        "unique_constraints": [],
        "description": "Site-level pre-shared key configurations",
    },
    "listSiteWebhooks": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "name", "type"],
        "unique_constraints": [],
        "description": "Site-level webhook configurations",
    },
    "listSiteWxRules": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "order"],
        "unique_constraints": [],
        "description": "Site-level WxLAN rules",
    },
    "listSiteWxTags": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "name", "type"],
        "unique_constraints": [],
        "description": "Site-level WxLAN tags",
    },
    "listSiteWxTunnels": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "name"],
        "unique_constraints": [],
        "description": "Site-level WxLAN tunnel configurations",
    },
    # Issue #172: Site-level client search endpoints
    "searchSiteWirelessClients": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id", "ssid", "ap"],
        "unique_constraints": [],
        "description": "Site-level wireless client search results",
    },
    "searchSiteWiredClients": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id", "device_mac"],
        "unique_constraints": [],
        "description": "Site-level wired client search results",
    },
    "searchSiteWanClients": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id", "hostname"],
        "unique_constraints": [],
        "description": "Site-level WAN client search results",
    },
    "searchSiteNacClients": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id"],
        "unique_constraints": [],
        "description": "Site-level NAC client search results",
    },
    "searchSiteNacClientEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "mac", "timestamp"],
        "indexes": ["site_id", "type", "nacrule_id"],
        "unique_constraints": [],
        "description": "Site-level NAC client event search results",
    },
    "searchSiteWirelessClientEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["site_id", "type", "ap", "ssid"],
        "unique_constraints": [],
        "description": "Site-level wireless client event search results",
    },
    "searchSiteWirelessClientSessions": {
        "type": "composite_pk",
        "primary_key": ["id", "mac", "timestamp"],
        "indexes": ["site_id", "ap", "ssid", "wlan_id"],
        "unique_constraints": [],
        "description": "Site-level wireless client session search results",
    },
    "searchSiteWanClientEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["site_id", "ev_type", "wcid"],
        "unique_constraints": [],
        "description": "Site-level WAN client event search results",
    },
    "listSiteUnconnectedClientStats": {
        "type": "composite_pk",
        "primary_key": ["mac", "map_id"],
        "indexes": ["mac", "map_id", "ap_mac"],
        "unique_constraints": [],
        "description": "Unconnected client statistics per map",
    },
    # Issue #171: Site-level device endpoints
    "searchSiteDevices": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id", "model", "type"],
        "unique_constraints": [],
        "description": "Site-level device search results",
    },
    "listSiteOtherDevices": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "device_mac", "vendor", "model"],
        "unique_constraints": [],
        "description": "Non-Juniper devices discovered at site",
    },
    "listSiteAvailableDeviceVersions": {
        "type": "composite_pk",
        "primary_key": ["model", "version"],
        "indexes": ["model", "tag"],
        "unique_constraints": [],
        "description": "Available firmware versions per device model",
    },
    "listSiteSpectrumAnalysis": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "band"],
        "unique_constraints": [],
        "description": "RF spectrum analysis data from AP radios",
    },
    "listSiteDeviceRadioChannels": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["key", "name", "code"],
        "unique_constraints": [],
        "description": "AP radio channel configuration per country",
    },
    "listSiteDeviceUpgrades": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["status", "target_version", "strategy"],
        "unique_constraints": [],
        "description": "Device firmware upgrade status and progress",
    },
    # Issue #184: Derived config endpoints (effective merged config at site)
    "listSiteWlansDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "ssid", "template_id"],
        "unique_constraints": [],
        "description": "Effective WLAN config after template inheritance",
    },
    "listSiteNetworksDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name", "vlan_id"],
        "unique_constraints": [],
        "description": "Effective network config after template inheritance",
    },
    "listSiteVpnsDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective VPN config after template inheritance",
    },
    "listSiteServicesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name", "type"],
        "unique_constraints": [],
        "description": "Effective service definitions after template inheritance",
    },
    "listSiteServicePoliciesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective service policies after template inheritance",
    },
    "listSiteUiSettingDerived": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "site_id"],
        "unique_constraints": [],
        "description": "Effective UI settings (object response, no array key)",
    },
    "listSiteAllGuestAuthorizationsDerived": {
        "type": "natural_pk",
        "primary_key": ["mac"],
        "indexes": ["site_id", "ssid", "wlan_id", "authorized"],
        "unique_constraints": [],
        "description": "Effective guest authorizations after template inheritance",
    },
    "listSiteApTemplatesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective AP template config after inheritance",
    },
    "listSiteRfTemplatesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective RF template config after inheritance",
    },
    "listSiteNetworkTemplatesDerived": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "site_id"],
        "unique_constraints": [],
        "description": "Effective network template (object response, no array key)",
    },
    "listSiteGatewayTemplatesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective gateway template config after inheritance",
    },
    "listSiteSiteTemplatesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective site template config after inheritance",
    },
    "listSiteDeviceProfilesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name", "type"],
        "unique_constraints": [],
        "description": "Effective device profiles after template inheritance",
    },
    "listSiteIdpProfilesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective IDP profiles after template inheritance",
    },
    "listSiteAAMWProfilesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective AAMW profiles after template inheritance",
    },
    "listSiteAntivirusProfilesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Effective antivirus profiles after template inheritance",
    },
    "listSiteSecIntelProfilesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id"],
        "unique_constraints": [],
        "description": "Effective SecIntel profiles after template inheritance",
    },
    # Type 4: Client search APIs (special handling for large datasets)
    "searchOrgWirelessClients": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id", "device_id", "ssid"],
        "unique_constraints": [],
        "description": "Wireless client data with composite key for time-series",
    },
    "searchOrgWiredClients": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id", "device_id", "port_id"],
        "unique_constraints": [],
        "description": "Wired client data with composite key for time-series",
    },
    "globalWiredClientReport": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id", "device_id", "manufacture"],
        "unique_constraints": [],
        "description": "Global wired client report with operator-based filtering",
    },
    "wiredClientManufacturerReport": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["mac", "timestamp", "site_id", "device_id", "manufacture"],
        "unique_constraints": [],
        "description": "Wired client report filtered by manufacturer selection",
    },
    # Type 5: License and summary APIs (often aggregated data)
    "getOrgLicensesSummary": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "sku", "type"],
        "unique_constraints": [],
        "description": "License summary data (aggregated, no stable primary key)",
    },
    "getOrgLicenseAsyncClaimStatus": {  # Register composite key strategy for claim-status summary snapshots.
        "type": "composite_pk",  # Use composite primary key because org_id + scheduled_at uniquely identifies one job.
        "primary_key": ["org_id", "scheduled_at"],  # Keep one row per org/job across repeated polls.
        "indexes": ["status"],  # Index status to accelerate prepared/ongoing/done filtering.
        "unique_constraints": [],  # Composite PK already enforces uniqueness without extra constraints.
        "table": "org_claim_status_summary",  # Persist summary rows to explicit SQLite table name.
        "description": "Async org claim job summary keyed by org and scheduled timestamp",  # Document storage intent.
    },
    "getOrgLicenseAsyncClaimStatusDetails": {  # Register detail-row strategy for per-device claim status records.
        "type": "composite_pk",  # Use composite key to avoid duplicate device rows per job.
        "primary_key": ["org_id", "scheduled_at", "mac"],  # Scope device status by org + job + device MAC.
        "indexes": ["mac"],  # Index MAC for fast per-device lookup queries.
        "unique_constraints": [],  # Composite PK provides uniqueness guarantee.
        "table": "org_claim_status_details",  # Persist detail rows to dedicated detail table.
        "description": "Async org claim detail rows keyed by org/job/mac",  # Describe per-device table purpose.
    },
    "listOrgLicenses": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "sku", "type"],
        "unique_constraints": [],
        "description": "License records from canonical list endpoint",
    },
    # Site Inventory Health Analysis reports
    "sitesMissingInfrastructure": {
        "type": "natural_pk",
        "primary_key": ["site_id"],
        "indexes": ["site_name", "missing_types", "ap_count"],
        "unique_constraints": [],
        "description": "Sites with APs but missing switches or gateways",
    },
    "sitesWithOfflineInfrastructure": {
        "type": "natural_pk",
        "primary_key": ["site_id"],
        "indexes": ["site_name", "offline_switches", "offline_gateways"],
        "unique_constraints": [],
        "description": "Sites with APs where switches or gateways are offline",
    },
    # E911 BSSID compliance report (derived data, one row per BSSID)
    "generateE911BSSIDReport": {
        "type": "natural_pk",
        "primary_key": ["bssid"],
        "indexes": ["site_name", "ap_name", "map_name"],
        "unique_constraints": [],
        "description": "E911 BSSID compliance report - one row per BSSID with location context",
    },
    # Default fallback strategy for unclassified endpoints
    # Uses auto-increment with unique constraint on API id field if present
    # Device Utility Commands - Diagnostic/Show command results (menus 123-157)
    "tracerouteFromDevice": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id", "command"],
        "unique_constraints": [],
        "description": "Traceroute results from device utility command",
    },
    "showSiteGatewayOspfNeighbors": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "OSPF neighbor table from gateway",
    },
    "showSiteGatewayOspfInterfaces": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "OSPF interface table from gateway",
    },
    "showSiteGatewayOspfDatabase": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "OSPF database from gateway",
    },
    "showSiteGatewayOspfSummary": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "OSPF summary from gateway",
    },
    "showSiteSsrAndSrxSessions": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "SSR/SRX session table",
    },
    "showSiteSsrServicePath": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "SSR service path table",
    },
    "showSiteDeviceBgpSummary": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "BGP summary table",
    },
    "showSiteDeviceArpTable": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "ARP table from device",
    },
    "showSiteDeviceDhcpLeases": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "DHCP lease table",
    },
    "showSiteDeviceDot1xTable": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "802.1X authentication table from switch",
    },
    "showSiteDeviceEvpnDatabase": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "EVPN database entries",
    },
    "testSiteSsrDnsResolution": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "DNS resolution test results from SSR",
    },
    "cableTestFromSwitch": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Cable test results from switch port",
    },
    # SSID Template Consolidation (Menu 159) strategies
    "ssidConsolidationMatrix": {
        "type": "composite_pk",
        "primary_key": ["site_id", "ssid_id"],
        "indexes": ["site_name", "template_id", "mxtunnel_id", "target_group"],
        "unique_constraints": [],
        "description": "SSID consolidation matrix - one row per site per target SSID",
    },
    "ssidConsolidationDeviation": {
        "type": "composite_pk",
        "primary_key": ["cluster_id", "parameter"],
        "indexes": ["cluster_name"],
        "unique_constraints": [],
        "description": "SSID parameter deviations within cluster groups",
    },
    "ssidConsolidationSiteVars": {
        "type": "composite_pk",
        "primary_key": ["site_id", "variable_name"],
        "indexes": ["site_name", "status"],
        "unique_constraints": [],
        "description": "Site variable assignments for SSID consolidation",
    },
    "ssidConsolidationSiteGroups": {
        "type": "composite_pk",
        "primary_key": ["site_id", "group_id"],
        "indexes": ["group_name", "status"],
        "unique_constraints": [],
        "description": "Site group assignments for SSID consolidation",
    },
    "ssidConsolidationTemplates": {
        "type": "composite_pk",
        "primary_key": ["template_id", "ssid_name"],
        "indexes": ["template_name", "group_name", "status"],
        "unique_constraints": [],
        "description": "Consolidated template creation results",
    },
    "ssidConsolidationDisable": {
        "type": "composite_pk",
        "primary_key": ["site_id", "ssid_id"],
        "indexes": ["old_template_id", "status"],
        "unique_constraints": [],
        "description": "Old SSID disable results for SSID consolidation",
    },
    # ========================================================================
    # ORG DATA COLLECTOR -- bulk collection endpoints (menu 165)
    # ========================================================================
    # -- Security Profiles (natural_pk) --------------------------------------
    "listOrgAAMWProfiles": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization Advanced Anti-Malware profiles",
    },
    "listOrgAntivirusProfiles": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization antivirus profiles",
    },
    "listOrgIdpProfiles": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization IDP profiles",
    },
    # -- Network & VPN (natural_pk) ------------------------------------------
    "listOrgVpns": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization VPN configurations",
    },
    "listOrgEvpnTopologies": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization EVPN topology configurations",
    },
    "listOrgWxTunnels": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization WxLAN tunnel configurations",
    },
    # -- Wireless Policy (natural_pk) ----------------------------------------
    "listOrgWxRules": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "order"],
        "unique_constraints": [],
        "description": "Organization WxLAN rules",
    },
    "listOrgWxTags": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization WxLAN tags",
    },
    # -- Edge Infrastructure -------------------------------------------------
    "listOrgMxEdgeClusters": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization MxEdge cluster configurations",
    },
    "listOrgMxEdgeUpgrades": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "mxedge_id", "status"],
        "unique_constraints": [],
        "description": "MxEdge firmware upgrade records",
    },
    # -- Device Management ---------------------------------------------------
    "listOrgDeviceUpgrades": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "site_id", "status"],
        "unique_constraints": [],
        "description": "Device firmware upgrade records",
    },
    "listOrgOtherDevices": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "mac", "vendor"],
        "unique_constraints": [],
        "description": "Non-Juniper devices tracked by the organization",
    },
    # -- Assets & Inventory --------------------------------------------------
    "listOrgAssets": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "mac", "site_id"],
        "unique_constraints": [],
        "description": "Organization BLE asset definitions",
    },
    "listOrgAssetFilters": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization asset filter rules",
    },
    "listOrgAssetsStats": {
        "type": "composite_pk",
        "primary_key": ["id", "mac", "timestamp"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Organization BLE asset statistics",
    },
    # -- JSI (Juniper Support Insights) --------------------------------------
    "listOrgJsiDevices": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "serial", "mac"],
        "unique_constraints": [],
        "description": "JSI-tracked device inventory",
    },
    "listOrgJsiPastPurchases": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "JSI historical purchase records",
    },
    # -- Access & Auth -------------------------------------------------------
    "listOrgCertificates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization TLS/SSL certificates",
    },
    "listOrgSsoRoles": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization SSO role mappings",
    },
    "listOrgSsoLatestFailures": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "timestamp"],
        "unique_constraints": [],
        "description": "Latest SSO authentication failures",
    },
    "listOrgIssuedClientCertificates": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Client certificates issued by the organization",
    },
    "listOrgNacPortalSsoLatestFailures": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "timestamp"],
        "unique_constraints": [],
        "description": "NAC portal SSO authentication failures",
    },
    "listOrgGuestAuthorizations": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "mac"],
        "unique_constraints": [],
        "description": "Guest network authorization records",
    },
    "listSiteAllGuestAuthorizations": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "mac", "wlan_id", "ap_mac"],
        "unique_constraints": [],
        "description": "Site-level guest WiFi authorization records",
    },
    # -- Site Rogues (insight-based, no API id field) -------------------------
    "listSiteRogueAPs": {
        "type": "composite_pk",
        "primary_key": ["bssid", "ap_mac"],
        "indexes": ["site_id", "ssid", "channel"],
        "unique_constraints": [],
        "description": "Rogue APs detected at a site via RF scanning",
    },
    "listSiteRogueClients": {
        "type": "composite_pk",
        "primary_key": ["client_mac", "bssid"],
        "indexes": ["site_id", "ap_mac", "band"],
        "unique_constraints": [],
        "description": "Rogue clients detected at a site via RF scanning",
    },
    # -- PSK Portals ---------------------------------------------------------
    "listOrgPskPortals": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization PSK portal configurations",
    },
    "listOrgPskPortalLogs": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["org_id", "psk_portal_id"],
        "unique_constraints": [],
        "description": "PSK portal access log entries",
    },
    # -- SDK & Invites -------------------------------------------------------
    "listSdkInvites": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "SDK invite records",
    },
    "listSdkTemplates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "SDK template definitions",
    },
    "listOrgMarvisClientInvites": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Marvis client invite records",
    },
    # -- Alarms & Tickets ----------------------------------------------------
    "listOrgSuppressedAlarms": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Suppressed alarm rules",
    },
    "listOrgTickets": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "status", "type"],
        "unique_constraints": [],
        "description": "Organization support tickets",
    },
    "getOrgTicket": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "status", "type"],
        "unique_constraints": [],
        "description": "Organization support ticket detail with comments",
    },
    # -- Dashboards & UI -----------------------------------------------------
    "listOrgPmaDashboards": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "PMA dashboard configurations",
    },
    "listOrgUiSettings": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Organization UI preference settings",
    },
    # -- Search Endpoints (composite_pk for time-series/event data) ----------
    "searchOrgDevices": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id", "site_id", "model", "type", "hostname"],
        "unique_constraints": [],
        "description": "Organization device search results",
    },
    "searchOrgDeviceLastConfigs": {
        "type": "composite_pk",
        "primary_key": ["device_id", "timestamp"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Last pushed device configurations",
    },
    "searchOrgInventory": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id", "site_id", "serial", "model", "type"],
        "unique_constraints": [],
        "description": "Organization inventory search results",
    },
    "searchOrgWirelessClientEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "mac", "timestamp"],
        "indexes": ["org_id", "site_id", "type", "ap"],
        "unique_constraints": [],
        "description": "Wireless client event search results",
    },
    "searchOrgWirelessClientSessions": {
        "type": "composite_pk",
        "primary_key": ["id", "mac", "timestamp"],
        "indexes": ["org_id", "site_id", "ap", "ssid"],
        "unique_constraints": [],
        "description": "Wireless client session search results",
    },
    "searchOrgWanClientEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "mac", "timestamp"],
        "indexes": ["org_id", "site_id", "type"],
        "unique_constraints": [],
        "description": "WAN client event search results",
    },
    "searchOrgWanClients": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id", "site_id", "hostname"],
        "unique_constraints": [],
        "description": "WAN client search results",
    },
    "searchOrgMistEdgeEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "mxedge_id", "timestamp"],
        "indexes": ["org_id", "type"],
        "unique_constraints": [],
        "description": "MistEdge event search results",
    },
    "searchOrgOtherDeviceEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "mac", "timestamp"],
        "indexes": ["org_id", "site_id", "type"],
        "unique_constraints": [],
        "description": "Other device event search results",
    },
    "searchOrgMxEdges": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id", "site_id", "name", "model"],
        "unique_constraints": [],
        "description": "MxEdge search results",
    },
    "searchOrgSites": {
        "type": "composite_pk",
        "primary_key": ["id", "name"],
        "indexes": ["org_id", "country_code"],
        "unique_constraints": [],
        "description": "Organization site search results",
    },
    "searchOrgOspfStats": {
        "type": "composite_pk",
        "primary_key": ["device_id", "neighbor", "timestamp"],
        "indexes": ["org_id", "site_id", "state"],
        "unique_constraints": [],
        "description": "OSPF neighbor statistics search results",
    },
    "searchOrgUserMacs": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Organization user MAC address search results",
    },
    "searchOrgPskPortalLogs": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["org_id", "psk_portal_id"],
        "unique_constraints": [],
        "description": "PSK portal log search results",
    },
    "searchOrgJsiAssetsAndContracts": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "serial"],
        "unique_constraints": [],
        "description": "JSI assets and contract search results",
    },
    "searchOrgJsiPbn": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "JSI PBN search results",
    },
    "searchOrgJsiSirt": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "JSI SIRT search results",
    },
    "searchOrgVars": {
        "type": "composite_pk",
        "primary_key": ["site_id", "name"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Organization variable search results",
    },
    "searchOrgWebhooksDeliveries": {
        "type": "composite_pk",
        "primary_key": ["id", "webhook_id", "timestamp"],
        "indexes": ["org_id", "status_code"],
        "unique_constraints": [],
        "description": "Webhook delivery search results",
    },
    # -- GET Endpoints (org-level summaries) ---------------------------------
    "getOrgSettings": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Organization settings snapshot",
    },
    "getOrgStats": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Organization-level statistics snapshot",
    },
    "getOrgApplicationList": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization application definitions",
    },
    # -- Count Endpoints (aggregated counts → auto_increment) ------------------
    "countOrgAlarms": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Organization alarm count aggregates",
    },
    "countOrgAssetsByDistanceField": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Asset count by distance field aggregates",
    },
    "countOrgAuditLogs": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Audit log count aggregates",
    },
    "countOrgBgpStats": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "BGP statistics count aggregates",
    },
    "countOrgDeviceEvents": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Device event count aggregates",
    },
    "countOrgDeviceLastConfigs": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Device last config count aggregates",
    },
    "countOrgDevices": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Device count aggregates",
    },
    "orgDeviceModelSummary": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "device_type", "model"],
        "unique_constraints": [],
        "description": "Device count by model across all device types (menu 187)",
    },
    "orgDeviceFirmwareSummary": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "device_type", "version"],
        "unique_constraints": [],
        "description": "Device count by firmware version and device type (menu 187)",
    },
    "orgDeviceVersionPerModel": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "device_type", "model", "version"],
        "unique_constraints": [],
        "description": "Device count by firmware version broken down per model (menu 187)",
    },
    "countOrgGuestAuthorizations": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Guest authorization count aggregates",
    },
    "countOrgInventory": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Inventory count aggregates",
    },
    "countOrgJsiAssetsAndContracts": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "JSI assets and contracts count aggregates",
    },
    "countOrgJsiPbn": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "JSI PBN count aggregates",
    },
    "countOrgJsiSirt": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "JSI SIRT count aggregates",
    },
    "countOrgMxEdges": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "MxEdge count aggregates",
    },
    "countOrgNacClientEvents": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "NAC client event count aggregates",
    },
    "countOrgNacClients": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "NAC client count aggregates",
    },
    "countOrgOspfStats": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "OSPF statistics count aggregates",
    },
    "countOrgOtherDeviceEvents": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Other device event count aggregates",
    },
    "countOrgPeerPathStats": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Peer path statistics count aggregates",
    },
    "countOrgPskPortalLogs": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "PSK portal log count aggregates",
    },
    "countOrgSiteMxEdgeEvents": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Site MxEdge event count aggregates",
    },
    "countOrgSites": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Site count aggregates",
    },
    "countOrgSwOrGwPorts": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Switch/gateway port count aggregates",
    },
    "countOrgSystemEvents": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "System event count aggregates",
    },
    "countOrgTickets": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Ticket count aggregates",
    },
    "createOrgTicket": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "status", "type"],
        "unique_constraints": [],
        "description": "Newly created organization support ticket",
    },
    "updateOrgTicket": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "status", "type"],
        "unique_constraints": [],
        "description": "Updated organization support ticket",
    },
    "addOrgTicketComment": {
        "type": "composite_pk",
        "primary_key": ["ticket_id", "created_at"],
        "indexes": ["ticket_id", "author"],
        "unique_constraints": [],
        "description": "Comment added to an organization support ticket",
    },
    "countOrgTunnelsStats": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Tunnel statistics count aggregates",
    },
    "countOrgUserMacs": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "User MAC address count aggregates",
    },
    "countOrgWanClients": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "WAN client count aggregates",
    },
    "countOrgWiredClients": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Wired client count aggregates",
    },
    "countOrgWirelessClientEvents": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Wireless client event count aggregates",
    },
    "countOrgWirelessClients": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Wireless client count aggregates",
    },
    "countOrgWirelessClientsSessions": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "distinct"],
        "unique_constraints": [],
        "description": "Wireless client session count aggregates",
    },
    # -- GET Endpoints (additional org-level data) ---------------------------
    "getOrg": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization details snapshot",
    },
    "getOrgCapturingStatus": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Organization packet capture status",
    },
    "getOrgLicensesBySite": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "site_id"],
        "unique_constraints": [],
        "description": "License allocation by site",
    },
    # -- LIST Endpoints (additional org-level entities) ----------------------
    "listOrgAdmins": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "email"],
        "unique_constraints": [],
        "description": "Organization administrator accounts",
    },
    "listOrgAlarmTemplates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization alarm template configurations",
    },
    "listOrgApiTokens": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization API token records",
    },
    "listOrgApsMacs": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "mac"],
        "unique_constraints": [],
        "description": "Organization AP MAC address list",
    },
    "listOrgAuditLogs": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["org_id", "admin_name", "message"],
        "unique_constraints": [],
        "description": "Organization audit log entries",
    },
    "listOrgAvailableDeviceVersions": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "model", "version"],
        "unique_constraints": [],
        "description": "Available firmware versions for org devices",
    },
    "listOrgAvailableSsrVersions": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "version"],
        "unique_constraints": [],
        "description": "Available SSR firmware versions",
    },
    "listOrgDeviceProfiles": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "type"],
        "unique_constraints": [],
        "description": "Organization device profile configurations",
    },
    "listOrgDevices": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "site_id", "mac", "serial", "model"],
        "unique_constraints": [],
        "description": "Organization devices list",
    },
    "listOrgDevicesSummary": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Organization device summary statistics",
    },
    "listOrgMxEdges": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "model"],
        "unique_constraints": [],
        "description": "Organization MxEdge appliances",
    },
    "listOrgMxEdgesStats": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id", "site_id", "name", "model"],
        "unique_constraints": [],
        "description": "Organization MxEdge statistics",
    },
    "listOrgMxTunnels": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization Mist tunnel configurations",
    },
    "listOrgNacPortals": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization NAC portal configurations",
    },
    "listOrgNacRules": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "order"],
        "unique_constraints": [],
        "description": "Organization NAC rules",
    },
    "listOrgNacTags": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "type"],
        "unique_constraints": [],
        "description": "Organization NAC tags",
    },
    "listOrgNetworks": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization network definitions",
    },
    "listOrgPacketCaptures": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["org_id", "site_id", "type"],
        "unique_constraints": [],
        "description": "Organization packet capture records",
    },
    "listOrgSecIntelProfiles": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization security intelligence profiles",
    },
    "listOrgServicePolicies": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization service policy configurations",
    },
    "listOrgServices": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "type"],
        "unique_constraints": [],
        "description": "Organization service definitions",
    },
    "listOrgSiteGroups": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization site group configurations",
    },
    "listOrgSiteStats": {
        "type": "composite_pk",
        "primary_key": ["id", "name"],
        "indexes": ["org_id", "country_code"],
        "unique_constraints": [],
        "description": "Organization site statistics",
    },
    "listOrgSsos": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization SSO configurations",
    },
    "listOrgSsrUpgrades": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id", "device_id", "status"],
        "unique_constraints": [],
        "description": "SSR firmware upgrade records",
    },
    "listOrgTemplates": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Organization WLAN template configurations",
    },
    "listOrgWlans": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "ssid"],
        "unique_constraints": [],
        "description": "Organization WLAN configurations",
    },
    # -- SEARCH Endpoints (additional) --------------------------------------
    "searchOrgAssets": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id", "site_id", "name"],
        "unique_constraints": [],
        "description": "Organization asset search results",
    },
    "searchOrgBgpStats": {
        "type": "composite_pk",
        "primary_key": ["device_id", "neighbor", "timestamp"],
        "indexes": ["org_id", "site_id", "state"],
        "unique_constraints": [],
        "description": "BGP neighbor statistics search results",
    },
    "searchOrgEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": ["org_id", "site_id", "type"],
        "unique_constraints": [],
        "description": "Organization event search results",
    },
    "searchOrgGuestAuthorization": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id", "site_id"],
        "unique_constraints": [],
        "description": "Guest authorization search results",
    },
    "searchSiteGuestAuthorization": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["site_id", "wlan_id", "ap_mac"],
        "unique_constraints": [],
        "description": "Site-level guest authorization search results",
    },
    "searchSiteRogueEvents": {
        "type": "composite_pk",
        "primary_key": ["bssid", "timestamp"],
        "indexes": ["site_id", "ap", "ssid"],
        "unique_constraints": [],
        "description": "Rogue AP/client event search results",
    },
    # -- Site MxEdge endpoints (issue #178) --
    "listSiteMxEdges": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "mac", "mxcluster_id"],
        "unique_constraints": [],
        "description": "Site MxEdge appliances",
    },
    "listSiteMxEdgesStats": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["site_id", "name", "status"],
        "unique_constraints": [],
        "description": "Site MxEdge statistics",
    },
    "searchSiteMistEdgeEvents": {
        "type": "composite_pk",
        "primary_key": ["mxedge_id", "timestamp"],
        "indexes": ["site_id", "mac", "type"],
        "unique_constraints": [],
        "description": "Site MxEdge event search results",
    },
    # -- Site Asset endpoints (issue #176) --
    "listSiteAssets": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "mac", "map_id", "name"],
        "unique_constraints": [],
        "description": "Site BLE asset definitions",
    },
    "searchSiteAssets": {
        "type": "composite_pk",
        "primary_key": ["mac", "map_id"],
        "indexes": ["site_id", "name", "device_name"],
        "unique_constraints": [],
        "description": "Site asset search results",
    },
    "listSiteAssetsStats": {
        "type": "composite_pk",
        "primary_key": ["mac", "map_id"],
        "indexes": ["site_id", "name", "device_name"],
        "unique_constraints": [],
        "description": "Site BLE asset statistics",
    },
    "listSiteDiscoveredAssets": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "mac", "map_id", "name"],
        "unique_constraints": [],
        "description": "Site discovered BLE assets",
    },
    "listSiteAssetFilters": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "name", "ap_mac"],
        "unique_constraints": [],
        "description": "Site asset filter rules",
    },
    # -- Site Applications, Calls, WAN Usage & Fingerprints (issue #183) --
    "listSiteApps": {
        "type": "composite_pk",
        "primary_key": ["key", "group"],
        "indexes": ["name"],
        "unique_constraints": [],
        "description": "Site application visibility",
    },
    "searchSiteCalls": {
        "type": "composite_pk",
        "primary_key": ["mac", "start_time"],
        "indexes": ["app", "meeting_id", "site_id", "rating"],
        "unique_constraints": [],
        "description": "Site call quality records",
    },
    "searchSiteWanUsage": {
        "type": "composite_pk",
        "primary_key": ["mac", "port_id", "peer_mac"],
        "indexes": ["policy", "tenant", "path_type"],
        "unique_constraints": [],
        "description": "Site WAN link usage",
    },
    "searchOrgClientFingerprints": {
        "type": "composite_pk",
        "primary_key": ["mac", "timestamp"],
        "indexes": ["site_id", "os_type", "mfg", "family"],
        "unique_constraints": [],
        "description": "Client NAC fingerprints",
    },
    "listSiteUiSettings": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "org_id", "name", "purpose"],
        "unique_constraints": [],
        "description": "Site UI dashboard settings",
    },
    "listSiteTroubleshootCalls": {
        "type": "composite_pk",
        "primary_key": ["meeting_id", "mac"],
        "indexes": ["site_id", "app"],
        "unique_constraints": [],
        "description": "Site call troubleshooting diagnostics",
    },
    # -- Issue #185: SLE impacted entity endpoints --
    "listSiteSlesMetrics": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": [],
        "unique_constraints": [],
        "description": "SLE metric availability per site scope",
    },
    "listSiteSleMetricClassifiers": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": [],
        "unique_constraints": [],
        "description": "SLE metric classifier breakdown",
    },
    "listSiteSleImpactedAps": {
        "type": "composite_pk",
        "primary_key": ["ap_mac", "metric", "classifier"],
        "indexes": ["name", "failure"],
        "unique_constraints": [],
        "description": "APs impacted by SLE metric degradation",
    },
    "listSiteSleImpactedSwitches": {
        "type": "composite_pk",
        "primary_key": ["switch_mac", "metric", "classifier"],
        "indexes": ["name", "failure"],
        "unique_constraints": [],
        "description": "Switches impacted by SLE metric degradation",
    },
    "listSiteSleImpactedGateways": {
        "type": "composite_pk",
        "primary_key": ["gateway_mac", "metric", "classifier"],
        "indexes": ["name", "failure"],
        "unique_constraints": [],
        "description": "Gateways impacted by SLE metric degradation",
    },
    "listSiteSleImpactedInterfaces": {
        "type": "composite_pk",
        "primary_key": ["switch_mac", "interface_name", "metric", "classifier"],
        "indexes": ["switch_name", "failure"],
        "unique_constraints": [],
        "description": "Switch interfaces impacted by SLE metric degradation",
    },
    "listSiteSleImpactedChassis": {
        "type": "composite_pk",
        "primary_key": ["switch_mac", "chassis", "metric", "classifier"],
        "indexes": ["role", "failure"],
        "unique_constraints": [],
        "description": "Switch chassis impacted by SLE metric degradation",
    },
    "listSiteSleImpactedWirelessClients": {
        "type": "composite_pk",
        "primary_key": ["mac", "metric", "classifier"],
        "indexes": ["name", "failure", "ssid"],
        "unique_constraints": [],
        "description": "Wireless clients impacted by SLE metric degradation",
    },
    "listSiteSleImpactedWiredClients": {
        "type": "composite_pk",
        "primary_key": ["mac", "metric", "classifier"],
        "indexes": ["name", "failure"],
        "unique_constraints": [],
        "description": "Wired clients impacted by SLE metric degradation",
    },
    "listSiteSleImpactedApplications": {
        "type": "composite_pk",
        "primary_key": ["app", "metric", "classifier"],
        "indexes": ["name", "failure"],
        "unique_constraints": [],
        "description": "Applications impacted by SLE metric degradation",
    },
    "searchOrgNacClientEvents": {
        "type": "composite_pk",
        "primary_key": ["id", "mac", "timestamp"],
        "indexes": ["org_id", "site_id", "type"],
        "unique_constraints": [],
        "description": "NAC client event search results",
    },
    "searchOrgNacClients": {
        "type": "composite_pk",
        "primary_key": ["id", "mac"],
        "indexes": ["org_id", "site_id"],
        "unique_constraints": [],
        "description": "NAC client search results",
    },
    "searchOrgTunnelsStats": {
        "type": "composite_pk",
        "primary_key": ["id", "device_id", "timestamp"],
        "indexes": ["org_id", "site_id"],
        "unique_constraints": [],
        "description": "Tunnel statistics search results",
    },
    # -- New operations for complete SDK coverage ----------------------------
    "getOrgJseInfo": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "JSE integration info",
    },
    "getOrgJseIntegration": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "JSE integration details",
    },
    "getOrgSkyAtpIntegration": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Sky ATP integration",
    },
    "getOrgZscalerIntegration": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Zscaler integration",
    },
    "getOrgMistScep": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Mist SCEP configuration",
    },
    "getOrgNacCrl": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "NAC CRL configuration",
    },
    "getOrgCrlFile": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "CRL file",
    },
    "getOrgSslProxyCert": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "SSL proxy certificate",
    },
    "getOrgAosRegisterCmd": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "AOS register command",
    },
    "getOrgSsrRegistrationCommands": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "SSR registration commands",
    },
    "getOrgMxEdgeUpgradeInfo": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "MxEdge upgrade info",
    },
    "getOrgSitesSle": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "Sites SLE metrics",
    },
    "countOrgWanClientEvents": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "WAN client events count",
    },
    # Default fallback strategy for unclassified endpoints
    # Uses auto-increment with unique constraint on API id field if present
    "default": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": [],  # Will be determined at runtime based on available fields
        "unique_constraints": [],  # Will be applied if 'id' field exists in data
        "description": "Fallback strategy with auto-increment primary key and unique constraint on API id",
    },
    "getOrgE911Report": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["org_id"],
        "unique_constraints": [],
        "description": "E911 report data for the organization",
    },
    "listSiteMxEdgeUpgrades": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "status"],
        "unique_constraints": [],
        "description": "MxEdge upgrade status records for a site",
    },
    "getSiteAutoMapAssignmentStatus": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Auto-map assignment status for a site",
    },
    "getSitesByAPModel": {
        "type": "natural_pk",
        "primary_key": ["site_id"],
        "indexes": ["org_id", "site_name", "ap_model", "ap_count"],
        "unique_constraints": [],
        "description": "Sites filtered by AP model with site address and AP count",
    },
    # ==============================
    # NET-NEW ENTRIES FROM PROBE RUN 3
    # 15 natural_pk + 3 composite_pk + key auto_increment reference endpoints
    # Added in version 26.05 to align EPKS with all reachable mistapi endpoints
    # ==============================
    # --- natural_pk (single-entity GET endpoints with stable UUID key) ---
    "getSiteInfo": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "country_code"],
        "unique_constraints": [],
        "description": "Full configuration snapshot for a single site",
    },
    "getSiteDevice": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "mac", "model", "type"],
        "unique_constraints": [],
        "description": "Single device configuration (AP, switch, or gateway) at a site",
    },
    "getSiteDeviceStats": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id", "mac", "type"],
        "unique_constraints": [],
        "description": "Runtime statistics for a single device at a site",
    },
    "getSiteDeviceVirtualChassis": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Virtual chassis topology for a single switch at a site",
    },
    "getOrgMxEdge": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Configuration for a single MxEdge appliance in the org",
    },
    "getOrgMxEdgeStats": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name"],
        "unique_constraints": [],
        "description": "Runtime statistics for a single MxEdge appliance in the org",
    },
    "getOrgWebhook": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["org_id", "name", "url"],
        "unique_constraints": [],
        "description": "Configuration for a single webhook endpoint in the org",
    },
    "getSiteAssetsOfInterest": {
        "type": "natural_pk",
        "primary_key": ["mac"],
        "indexes": ["site_id", "name"],
        "unique_constraints": [],
        "description": "Tracked BLE/WiFi assets flagged as assets of interest at a site",
    },
    "getSiteSetting": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Full settings object for a single site (single-row result)",
    },
    "getSiteSettingDerived": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Derived (merged org + site) settings for a single site",
    },
    "getSiteWxRulesUsage": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "WxLAN rule usage statistics for a site (aggregate, no stable key)",
    },
    "ListSiteWxRulesDerived": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "WxLAN rules with org-level inheritance resolved for a site",
    },
    "getSiteSiteRfdiagRecording": {
        "type": "natural_pk",
        "primary_key": ["id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "RF diagnostics recording for a site",
    },
    "listSiteBeaconsStats": {
        "type": "composite_pk",
        "primary_key": ["id", "site_id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "BLE beacon statistics per site (composite key: beacon id + site)",
    },
    # --- composite_pk (no single stable UUID; identity is multi-field) ---
    "getSiteCurrentChannelPlanning": {
        "type": "composite_pk",
        "primary_key": ["ap", "band"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Current RRM channel and power plan per AP radio at a site",
    },
    "listNacEventsDefinitions": {
        "type": "composite_pk",
        "primary_key": ["key"],
        "indexes": [],
        "unique_constraints": [],
        "description": "NAC event type definitions and descriptions (reference data)",
    },
    "listSelfAuditLogs": {
        "type": "composite_pk",
        "primary_key": ["id", "timestamp"],
        "indexes": [],
        "unique_constraints": [],
        "description": "Audit log of changes made by the authenticated admin account",
    },
    # --- auto_increment_with_unique (site/org summary objects without stable keys) ---
    "getSiteStats": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Aggregate health and capacity statistics for a site",
    },
    "getSiteGatewayMetrics": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Gateway performance metrics summary for a site",
    },
    "getSiteSwitchesMetrics": {
        "type": "auto_increment_with_unique",
        "primary_key": ["misthelper_internal_id"],
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "Switch performance metrics summary for a site",
    },
    # --- HA Gateway Cluster ---
    "GetSiteDeviceHaClusterNode": {
        "type": "composite_pk",
        "primary_key": ["site_id", "device_id"],  # Each device has one HA node record per site
        "indexes": ["site_id"],
        "unique_constraints": [],
        "description": "HA cluster node membership (node0/node1 MAC pair) for a gateway at a site",
    },
    "listSiteGatewayHaStats": {
        "type": "composite_pk",
        "primary_key": ["site_id", "mac"],  # Gateway MAC is unique per site
        "indexes": ["site_id", "is_ha", "node_name"],
        "unique_constraints": [],
        "description": "Combined HA gateway stats and cluster node membership for all HA gateways at a site",
    },
}
